-- ----- fragment: minion_hebrews_11.sql (S222 Hebrews 11) -----
-- =====================================================================
-- S222 minion — HEBREWS 11 FULL-LIBRARY cross-references
-- =====================================================================
-- Chapter: HEBREWS 11.  Tag: h11 (temp view _s222_h11_lookup).  Sort band: 7971, step 1 (<=7979).
-- Source is ALWAYS the canon Hebrews verse; targets span Tanakh + extra-canonical.
-- Tiers per-row: canon target = 'free'; extra-canonical target = 'extras'.
--
-- GOVERNING FRAME: Hebrews 11 is the faith/faithfulness (emunah) cloud — faith demonstrated by
-- obedient action, never mere mental assent. *Now faith is the substance of things hoped for, the
-- evidence of things not seen* (11:1): each witness is named for what faith MOVED him to DO — Abel
-- offered, Enoch walked and pleased Elohim, Noah prepared an ark, Abraham obeyed and went out and
-- offered Isaac, Moses refused Pharaoh's house and esteemed the reproach of Messiah, the prophets
-- subdued kingdoms and stopped lions' mouths, the martyrs were tortured and would not accept
-- deliverance that they might obtain a better resurrection. The extras layer is essential here: the
-- Enoch translation tradition (1 Enoch, Jubilees 4, Sirach 44:16) and the Maccabean martyrs
-- (2 Maccabees 7) carry witnesses the canon names only in summary. *These all died in faith, not
-- having received the promises... Elohim having provided some better thing for us* (11:13, 39-40) —
-- the faithful of every age wait together for the one resurrection.
--
-- PER-CHAPTER LIBRARY-COVERAGE CHECKLIST (all three weighed for every verse-block):
--   v.1,3   faith the substance / the worlds framed by the word of Elohim
--           Tanakh: Genesis 1:1, Genesis 1:3 (the worlds framed by his word)  Extras: none warranted  NT: none added (carried in prose)
--   v.4     Abel's more excellent sacrifice
--           Tanakh: Genesis 4:4, Genesis 4:10 (the blood crieth)  Extras: Jubilees 4:2-3 (the offering accepted; the blood cried from the ground)  NT: none warranted
--   v.5-6   Enoch translated that he should not see death; pleased Elohim
--           Tanakh: Genesis 5:24 (walked with Elohim; was not, Elohim took him)  Extras: 1 Enoch 71:1,5 (spirit translated, ascended into the heavens), Jubilees 4:23 (taken from amongst the children of men, conducted into the Garden), Ecclesiasticus 44:16 (Enoch pleased Yahuah and was translated)  NT: none warranted
--   v.7     Noah warned of things not seen, prepared an ark
--           Tanakh: Genesis 6:13-14 (the end of all flesh; make thee an ark), Genesis 6:22 (so did Noah)  Extras: Ecclesiasticus 44:17 (Noah found perfect; left as a remnant)  NT: none warranted
--   v.8-19  Abraham called out, looked for a city, Sarah received strength, offered Isaac
--           Tanakh: Genesis 12:1 (get thee out), Genesis 15:5 (seed as the stars), Genesis 18:14 (is anything too hard), Genesis 21:2 (Sarah conceived), Genesis 22:2 (offer up Isaac), Genesis 22:17 (in blessing I will bless)  Extras: Ecclesiasticus 44:20-21 (proved and found faithful; the oath, the seed as the stars)  NT: none warranted
--   v.20-22 Isaac, Jacob, Joseph blessing; the bones of Joseph
--           Tanakh: Genesis 27:27-29 (Isaac blessed Jacob), Genesis 48:15-16 (Jacob blessed Joseph's sons), Genesis 50:24-25 (Joseph: carry up my bones)  Extras: none warranted  NT: none warranted
--   v.23-31 Moses refused Pharaoh's house, the passover/Red Sea, Jericho, Rahab
--           Tanakh: Exodus 2:2 (hid three months), Exodus 2:11 (looked on his brethren), Joshua 6:20 (the wall fell down flat), Joshua 2:11 (Rahab's confession), Joshua 6:25 (Rahab saved)  Extras: none warranted  NT: none warranted
--   v.32-35a prophets subdued kingdoms, stopped lions' mouths, quenched fire; women's dead raised
--           Tanakh: Daniel 6:22 (the lions' mouths shut), Daniel 3:27 (the fire had no power), 1 Kings 17:22 (the child's soul came again), 2 Kings 4:35 (the child sneezed and opened his eyes)  Extras: none warranted  NT: none warranted
--   v.35b-40 others tortured, not accepting deliverance, for a better resurrection
--           Tanakh: none warranted (the canon names the martyrs only in summary)  Extras: 2 Maccabees 7:9, 7:11, 7:14, 7:23, 7:29 (the mother and seven sons; raised up to everlasting life; receive them again)  NT: none warranted
--
-- THREADS (slug -> target libraries):
--   7971 hebrews-11-faith-the-substance-of-things-hoped-for-the-worlds-framed-genesis-1       (Tanakh)
--   7972 hebrews-11-abel-a-more-excellent-sacrifice-genesis-4                                  (Tanakh + extras: Jubilees)
--   7973 hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5                    (Tanakh + extras: 1 Enoch, Jubilees, Sirach)
--   7974 hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6                   (Tanakh + extras: Sirach)
--   7975 hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22                  (Tanakh + extras: Sirach)
--   7976 hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50          (Tanakh)
--   7977 hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6  (Tanakh)
--   7978 hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6   (Tanakh)
--   7979 hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees   (extras: 2 Maccabees)
-- =====================================================================

CREATE TEMP VIEW _s222_h11_lookup AS
SELECT e.slug AS edition_slug, b.slug AS book_slug, c.chapter_number, v.verse_number, v.id AS verse_id
  FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
  JOIN editions e ON b.edition_id = e.id
 WHERE e.slug IN ('canon','enoch','jubilees','jasher','apocrypha','apocrypha-charles-vol1','pseudepigrapha','adam-eve-conflict','apocalypse-of-abraham','ascension-isaiah','sonnini-acts-29');

WITH input(src_edition, src_slug, src_ch, src_v,
           tgt_edition, tgt_slug, tgt_ch, tgt_v, tier, note) AS (VALUES
  -- thread: hebrews-11-faith-the-substance-of-things-hoped-for-the-worlds-framed-genesis-1
  ('canon', 'hebrews', 11, 3, 'canon', 'genesis', 1, 1, 'free', E'*In the beginning Elohim (God) created the heaven and the earth.* (Genesis 1:1). *Through faith we understand that the worlds were framed by the word of Elohim (God), so that things which are seen were not made of things which do appear* (Hebrews 11:3). The very first line of the Torah is the first act of faith the writer names: the worlds had no maker but the word of Elohim, and no material but his speaking. *Faith is the substance of things hoped for, the evidence of things not seen* (Hebrews 11:1) — and the unseen word that framed the seen creation is the ground of all that follows.'),
  ('canon', 'hebrews', 11, 3, 'canon', 'genesis', 1, 3, 'free', E'*And Elohim (God) said, Let there be light: and there was light.* (Genesis 1:3). *Through faith we understand that the worlds were framed by the word of Elohim (God), so that things which are seen were not made of things which do appear* (Hebrews 11:3). The pattern of the whole chapter is set here: Elohim speaks, and what was not seen becomes seen. *Let there be light: and there was light* is the word framing the world out of no prior thing — exactly the unseen-becoming-evidence that faith lays hold of.'),
  -- thread: hebrews-11-abel-a-more-excellent-sacrifice-genesis-4
  ('canon', 'hebrews', 11, 4, 'canon', 'genesis', 4, 4, 'free', E'*And Abel, he also brought of the firstlings of his flock and of the fat thereof. And Yahuah (LORD) had respect unto Abel and to his offering:* (Genesis 4:4). *By faith Abel offered unto Elohim (God) a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, Elohim (God) testifying of his gifts* (Hebrews 11:4). The first man of faith brought the firstlings and the fat — the best, given in trust — and Yahuah had respect unto it. The respect Yahuah showed the offering is the very witness Hebrews names: Elohim *testifying of his gifts* that Abel was righteous.'),
  ('canon', 'hebrews', 11, 4, 'canon', 'genesis', 4, 10, 'free', E'*And he said, What hast thou done? the voice of thy brother''s blood crieth unto me from the ground.* (Genesis 4:10). *By faith Abel offered... and by it he being dead yet speaketh* (Hebrews 11:4). Abel is dead, and yet he speaks — the writer hears the same voice Yahuah heard: *the voice of thy brother''s blood crieth unto me from the ground.* The righteous man slain is not silenced; his blood still cries, and his faith still witnesses to every generation that comes after.'),
  ('canon', 'hebrews', 11, 4, 'jubilees', 'jubilees', 4, 2, 'extras', E'*And in the first (year) of the third jubilee, Cain slew Abel because Elohim (God) accepted the sacrifice of Abel, and did not accept the offering of Cain.* (Jubilees 4:2). *By faith Abel offered unto Elohim (God) a more excellent sacrifice than Cain* (Hebrews 11:4). Jubilees names plainly what Genesis shows and Hebrews weighs: Elohim *accepted the sacrifice of Abel, and did not accept the offering of Cain.* The acceptance is the witness; the rejected brother''s murder follows the accepted brother''s faith.'),
  ('canon', 'hebrews', 11, 4, 'jubilees', 'jubilees', 4, 3, 'extras', E'*And he slew him in the field: and his blood cried from the ground to heaven, complaining because he had slain him.* (Jubilees 4:3). *By faith Abel offered... and by it he being dead yet speaketh* (Hebrews 11:4). Jubilees hears the same crying blood the writer of Hebrews hears: *his blood cried from the ground to heaven.* The dead man speaks still — the blood of the first faithful witness lifting its voice to heaven, the pattern of every righteous one slain for his offering after him.'),
  -- thread: hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5
  ('canon', 'hebrews', 11, 5, 'canon', 'genesis', 5, 24, 'free', E'*And Enoch walked with Elohim (God): and he was not; for Elohim (God) took him.* (Genesis 5:24). *By faith Enoch was translated that he should not see death; and was not found, because Elohim (God) had translated him: for before his translation he had this testimony, that he pleased Elohim (God)* (Hebrews 11:5). The Torah''s spare line — *he was not; for Elohim took him* — is the translation Hebrews names. Enoch alone in the genealogy of death does not die; the man who *walked with Elohim* is taken by Elohim, the testimony of a life that pleased him.'),
  ('canon', 'hebrews', 11, 5, 'enoch', '1-enoch', 71, 1, 'extras', E'*And it came to pass after this that my spirit was carried off and it ascended into the heavens: And I saw the holy sons of Elohim (God).* (1 Enoch 71:1). *By faith Enoch was translated that he should not see death... because Elohim (God) had translated him* (Hebrews 11:5). The Torah says only that Elohim took him; the Enoch tradition shows the taking from the inside — *my spirit was carried off and it ascended into the heavens.* The man who pleased Elohim is brought up among *the holy sons of Elohim,* translated rather than buried.'),
  ('canon', 'hebrews', 11, 5, 'enoch', '1-enoch', 71, 5, 'extras', E'*And he translated my spirit into the heaven of heavens, And I saw there a structure built of crystals, And between those crystals tongues of living fire.* (1 Enoch 71:5). *By faith Enoch was translated that he should not see death* (Hebrews 11:5). The word Hebrews uses for Enoch — *translated* — is the word the vision uses: *he translated my spirit into the heaven of heavens.* The witness who would not see death is carried into the very dwelling-place of Elohim, among the first fathers and the righteous who dwell there from the beginning of the world.'),
  ('canon', 'hebrews', 11, 5, 'jubilees', 'jubilees', 4, 23, 'extras', E'*And he was taken from amongst the children of men, and we conducted him into the Garden of Eden in majesty and honour, and behold there he writes down the condemnation and judgment of the world, and all the wickedness of the children of men.* (Jubilees 4:23). *By faith Enoch was translated that he should not see death; and was not found, because Elohim (God) had translated him* (Hebrews 11:5). Jubilees fills out the *was not found* of the Torah: Enoch *was taken from amongst the children of men,* conducted *in majesty and honour* into the Garden. The man who pleased Elohim is removed from the company of the dying and set in the place of the living.'),
  ('canon', 'hebrews', 11, 5, 'apocrypha', 'ecclesiasticus', 44, 16, 'extras', E'*Enoch pleased Yahuah (God), and was translated, being an example of repentance to all generations.* (Ecclesiasticus 44:16). *By faith Enoch was translated that he should not see death... for before his translation he had this testimony, that he pleased Elohim (God)* (Hebrews 11:5). Ben Sira and the writer of Hebrews use the same two words of the same man: he *pleased* Elohim, and he *was translated.* The testimony that he pleased Elohim is the cause; the translation is its seal.'),
  ('canon', 'hebrews', 11, 6, 'canon', 'genesis', 5, 24, 'free', E'*And Enoch walked with Elohim (God): and he was not; for Elohim (God) took him.* (Genesis 5:24). *But without faith it is impossible to please him: for he that cometh to Elohim (God) must believe that he is, and that he is a rewarder of them that diligently seek him* (Hebrews 11:6). Enoch is the proof of the principle the writer draws out: a man who *walked with Elohim* is a man who believed *that he is* and sought him diligently — and the reward of that seeking was to be taken to him rather than left to death.'),
  -- thread: hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6
  ('canon', 'hebrews', 11, 7, 'canon', 'genesis', 6, 13, 'free', E'*And Elohim (God) said unto Noah, The end of all flesh is come before me; for the earth is filled with violence through them; and, behold, I will destroy them with the earth.* (Genesis 6:13). *By faith Noah, being warned of Elohim (God) of things not seen as yet, moved with fear, prepared an ark to the saving of his house* (Hebrews 11:7). The warning of *things not seen as yet* is this word: a flood not yet come, an end of all flesh announced before a drop had fallen. Noah believed the unseen word and built — faith laying hold of the evidence of what could not yet be seen.'),
  ('canon', 'hebrews', 11, 7, 'canon', 'genesis', 6, 14, 'free', E'*Make thee an ark of gopher wood; rooms shalt thou make in the ark, and shalt pitch it within and without with pitch.* (Genesis 6:14). *By faith Noah... moved with fear, prepared an ark to the saving of his house* (Hebrews 11:7). The command to *make thee an ark* is the obedient action faith produced. Noah did not see the water; he heard the word and took up the gopher wood. The ark itself is faith made visible — the substance of a thing hoped for, framed plank by plank against an unseen judgment.'),
  ('canon', 'hebrews', 11, 7, 'canon', 'genesis', 6, 22, 'free', E'*Thus did Noah; according to all that Elohim (God) commanded him, so did he.* (Genesis 6:22). *By faith Noah... prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith* (Hebrews 11:7). *According to all that Elohim commanded him, so did he* is the whole of Noah''s faith in one line — not assent but obedience, the doing of all that was commanded. The righteousness which is by faith is the righteousness of the man who *did* the word he could not yet see fulfilled.'),
  ('canon', 'hebrews', 11, 7, 'apocrypha', 'ecclesiasticus', 44, 17, 'extras', E'*Noah was found perfect and righteous; in the time of wrath he was taken in exchange for the world; therefore was he left as a remnant to the earth, when the flood came.* (Ecclesiasticus 44:17). *By faith Noah... became heir of the righteousness which is by faith* (Hebrews 11:7). Ben Sira names the same righteousness Hebrews names — Noah *found perfect and righteous* — and adds the office it carried: *left as a remnant to the earth.* The faithful builder is the seed through whom the world goes on, the heir of righteousness preserved through the wrath.'),
  -- thread: hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22
  ('canon', 'hebrews', 11, 8, 'canon', 'genesis', 12, 1, 'free', E'*Now Yahuah (LORD) had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father''s house, unto a land that I will shew thee:* (Genesis 12:1). *By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went* (Hebrews 11:8). The call is exactly *get thee out... unto a land that I will shew thee* — a destination withheld, an inheritance promised but unseen. Abraham *obeyed; and he went out, not knowing whither he went* — faith walking on the bare word of Yahuah.'),
  ('canon', 'hebrews', 11, 11, 'canon', 'genesis', 18, 14, 'free', E'*Is any thing too hard for Yahuah (LORD)? At the time appointed I will return unto thee, according to the time of life, and Sarah shall have a son.* (Genesis 18:14). *Through faith also Sara herself received strength to conceive seed, and was delivered of a child when she was past age, because she judged him faithful who had promised* (Hebrews 11:11). The promise that drew Sarah''s faith is this word at the tent door: *is anything too hard for Yahuah?* She *judged him faithful who had promised,* and the One who cannot fail in his word gave the strength to conceive past age.'),
  ('canon', 'hebrews', 11, 11, 'canon', 'genesis', 21, 2, 'free', E'*For Sarah conceived, and bare Abraham a son in his old age, at the set time of which Elohim (God) had spoken to him.* (Genesis 21:2). *Through faith also Sara herself received strength to conceive seed, and was delivered of a child when she was past age, because she judged him faithful who had promised* (Hebrews 11:11). The faith is vindicated in the birth: *Sarah conceived, and bare Abraham a son in his old age, at the set time of which Elohim had spoken.* The set time kept proves the One who promised faithful — the substance of a thing hoped for made flesh in Isaac.'),
  ('canon', 'hebrews', 11, 12, 'canon', 'genesis', 15, 5, 'free', E'*And he brought him forth abroad, and said, Look now toward heaven, and tell the stars, if thou be able to number them: and he said unto him, So shall thy seed be.* (Genesis 15:5). *Therefore sprang there even of one, and him as good as dead, so many as the stars of the sky in multitude, and as the sand which is by the sea shore innumerable* (Hebrews 11:12). The seed *as the stars of the sky* is the very promise of the night Yahuah brought Abraham forth: *tell the stars... so shall thy seed be.* From one man *as good as dead* came the innumerable seed, because he believed the star-promise of the unseen.'),
  ('canon', 'hebrews', 11, 17, 'canon', 'genesis', 22, 2, 'free', E'*And he said, Take now thy son, thine only son Isaac, whom thou lovest, and get thee into the land of Moriah; and offer him there for a burnt offering upon one of the mountains which I will tell thee of.* (Genesis 22:2). *By faith Abraham, when he was tried, offered up Isaac: and he that had received the promises offered up his only begotten son* (Hebrews 11:17). The trial Hebrews names is this command — *take now thy son, thine only son Isaac... and offer him.* The man who held the promise of seed through Isaac was asked to lay Isaac on the altar, and by faith he obeyed.'),
  ('canon', 'hebrews', 11, 18, 'canon', 'genesis', 22, 17, 'free', E'*That in blessing I will bless thee, and in multiplying I will multiply thy seed as the stars of the heaven, and as the sand which is upon the sea shore; and thy seed shall possess the gate of his enemies;* (Genesis 22:17). *Of whom it was said, That in Isaac shall thy seed be called: Accounting that Elohim (God) was able to raise him up, even from the dead* (Hebrews 11:18-19). The oath sworn on the mount Abraham climbed with his son — *in blessing I will bless thee, and in multiplying I will multiply thy seed* — is why he could lift the knife: the seed was promised through Isaac, so Elohim must be *able to raise him up, even from the dead.* Faith reasoned to resurrection from the unbreakable promise.'),
  ('canon', 'hebrews', 11, 17, 'apocrypha', 'ecclesiasticus', 44, 20, 'extras', E'*Who kept the law of the Most High, and was in covenant with him: he established the covenant in his flesh; and when he was proved, he was found faithful.* (Ecclesiasticus 44:20). *By faith Abraham, when he was tried, offered up Isaac* (Hebrews 11:17). Ben Sira and Hebrews name the same testing of the same man: *when he was proved, he was found faithful.* The faith that is faithfulness — kept law, covenant in the flesh, the proving on Moriah — is the obedient trust Hebrews crowns. Abraham was *tried* and *found faithful.*'),
  ('canon', 'hebrews', 11, 12, 'apocrypha', 'ecclesiasticus', 44, 21, 'extras', E'*Therefore he assured him by an oath, that he would bless the nations in his seed, and that he would multiply him as the dust of the earth, and exalt his seed as the stars, and cause them to inherit from sea to sea, and from the river to the utmost part of the land.* (Ecclesiasticus 44:21). *Therefore sprang there even of one, and him as good as dead, so many as the stars of the sky in multitude* (Hebrews 11:12). The oath Ben Sira recalls — *exalt his seed as the stars* — is the ground of the innumerable multitude Hebrews counts. From the one man came the seed as the stars because Yahuah *assured him by an oath,* and the faithful one believed the oath.'),
  -- thread: hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50
  ('canon', 'hebrews', 11, 20, 'canon', 'genesis', 27, 27, 'free', E'*And he came near, and kissed him: and he smelled the smell of his raiment, and blessed him, and said, See, the smell of my son is as the smell of a field which Yahuah (LORD) hath blessed:* (Genesis 27:27). *By faith Isaac blessed Jacob and Esau concerning things to come* (Hebrews 11:20). The blessing Isaac pronounced over Jacob — dew of heaven, fatness of the earth, dominion — was faith reaching into *things to come,* speaking over an unseen future as though already given. The aged, dim-eyed patriarch blessed by faith, and the word held.'),
  ('canon', 'hebrews', 11, 21, 'canon', 'genesis', 48, 15, 'free', E'*And he blessed Joseph, and said, Elohim (God), before whom my fathers Abraham and Isaac did walk, the Elohim (God) which fed me all my life long unto this day,* (Genesis 48:15). *By faith Jacob, when he was a dying, blessed both the sons of Joseph; and worshipped, leaning upon the top of his staff* (Hebrews 11:21). The dying Jacob blessed Ephraim and Manasseh by faith, naming *the Elohim before whom my fathers Abraham and Isaac did walk* — binding the generation to come into the covenant of the fathers, and worshipping as he leaned upon his staff.'),
  ('canon', 'hebrews', 11, 21, 'canon', 'genesis', 48, 16, 'free', E'*The Angel which redeemed me from all evil, bless the lads; and let my name be named on them, and the name of my fathers Abraham and Isaac; and let them grow into a multitude in the midst of the earth.* (Genesis 48:16). *By faith Jacob, when he was a dying, blessed both the sons of Joseph* (Hebrews 11:21). The blessing crosses his hands over Joseph''s sons and calls on *the Angel which redeemed me from all evil* — the dying man''s faith setting the covenant name on the lads, that they *grow into a multitude in the midst of the earth.* Faith blessed the unseen multitude into being.'),
  ('canon', 'hebrews', 11, 22, 'canon', 'genesis', 50, 24, 'free', E'*And Joseph said unto his brethren, I die: and Elohim (God) will surely visit you, and bring you out of this land unto the land which he sware to Abraham, to Isaac, and to Jacob.* (Genesis 50:24). *By faith Joseph, when he died, made mention of the departing of the children of Yashar''el (Israel); and gave commandment concerning his bones* (Hebrews 11:22). The departing Joseph foretold is this dying word: *Elohim will surely visit you, and bring you out of this land unto the land which he sware.* Faith saw the exodus generations before it came, certain of the oath to the fathers.'),
  ('canon', 'hebrews', 11, 22, 'canon', 'genesis', 50, 25, 'free', E'*And Joseph took an oath of the children of Yashar''el (Israel), saying, Elohim (God) will surely visit you, and ye shall carry up my bones from hence.* (Genesis 50:25). *By faith Joseph, when he died... gave commandment concerning his bones* (Hebrews 11:22). The commandment concerning his bones is this oath: *ye shall carry up my bones from hence.* So sure was Joseph of the visitation and the land that he bound the people to carry his bones home — faith staking even his burial on a promise not yet seen.'),
  -- thread: hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6
  ('canon', 'hebrews', 11, 23, 'canon', 'exodus', 2, 2, 'free', E'*And the woman conceived, and bare a son: and when she saw him that he was a goodly child, she hid him three months.* (Exodus 2:2). *By faith Moses, when he was born, was hid three months of his parents, because they saw he was a proper child; and they were not afraid of the king''s commandment* (Hebrews 11:23). The hiding Hebrews names is this — *she hid him three months* — set against Pharaoh''s edict to drown the sons. The parents'' faith was the first act of the deliverer''s story: they feared Elohim and not *the king''s commandment.*'),
  ('canon', 'hebrews', 11, 24, 'canon', 'exodus', 2, 11, 'free', E'*And it came to pass in those days, when Moses was grown, that he went out unto his brethren, and looked on their burdens: and he spied an Egyptian smiting an Hebrew, one of his brethren.* (Exodus 2:11). *By faith Moses, when he was come to years, refused to be called the son of Pharaoh''s daughter; Choosing rather to suffer affliction with the people of Elohim (God)* (Hebrews 11:24-25). Moses *come to years* went out to *his brethren* and owned their burdens as his own — the refusal of Pharaoh''s house enacted. He esteemed *the reproach of Messiah greater riches than the treasures in Egypt* (Hebrews 11:26), choosing the afflicted people of Elohim over the court that raised him.'),
  ('canon', 'hebrews', 11, 29, 'canon', 'exodus', 14, 22, 'free', E'*And the children of Yashar''el (Israel) went into the midst of the sea upon the dry ground: and the waters were a wall unto them on their right hand, and on their left.* (Exodus 14:22). *By faith they passed through the Red sea as by dry land: which the Egyptians assaying to do were drowned* (Hebrews 11:29). The passage Hebrews names is this crossing — *into the midst of the sea upon the dry ground,* the waters a wall on either hand. The same path that saved the believing drowned the pursuers; faith walked the dry land between the standing waters.'),
  ('canon', 'hebrews', 11, 30, 'canon', 'joshua', 6, 20, 'free', E'*So the people shouted when the priests blew with the trumpets... that the wall fell down flat, so that the people went up into the city, every man straight before him, and they took the city.* (Joshua 6:20). *By faith the walls of Jericho fell down, after they were compassed about seven days* (Hebrews 11:30). The falling wall Hebrews names is this — *the wall fell down flat* at the trumpet and the shout, after the seven days'' compassing. No ram, no siege; only the obedience of faith circling the city until Yahuah threw down the stones.'),
  ('canon', 'hebrews', 11, 31, 'canon', 'joshua', 2, 11, 'free', E'*And as soon as we had heard these things, our hearts did melt, neither did there remain any more courage in any man, because of you: for Yahuah Elohaychem (the LORD your God), he is Elohim (God) in heaven above, and in earth beneath.* (Joshua 2:11). *By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace* (Hebrews 11:31). Rahab''s faith is this confession in the doomed city: *Yahuah your Elohim, he is Elohim in heaven above, and in earth beneath.* While the city *believed not,* she believed, and received the spies with peace — and was saved out of Jericho''s fall.'),
  ('canon', 'hebrews', 11, 31, 'canon', 'joshua', 6, 25, 'free', E'*And Joshua saved Rahab the harlot alive, and her father''s household, and all that she had; and she dwelleth in Yashar''el (Israel) even unto this day; because she hid the messengers, which Joshua sent to spy out Jericho.* (Joshua 6:25). *By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace* (Hebrews 11:31). The saving Hebrews names is this — *Joshua saved Rahab the harlot alive... and she dwelleth in Yashar''el even unto this day.* The foreign woman who believed is absorbed into the covenant people and her faith made her dwelling there; the rest of the city perished.'),
  -- thread: hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6
  ('canon', 'hebrews', 11, 33, 'canon', 'daniel', 6, 22, 'free', E'*My Elohim (God) hath sent his angel, and hath shut the lions'' mouths, that they have not hurt me: forasmuch as before him innocency was found in me; and also before thee, O king, have I done no hurt.* (Daniel 6:22). *Who through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions* (Hebrews 11:33). The stopping of the lions'' mouths Hebrews names is this night in the den: *my Elohim hath sent his angel, and hath shut the lions'' mouths.* Daniel would not cease his prayer at the king''s decree, and his faith kept him whole among the lions.'),
  ('canon', 'hebrews', 11, 34, 'canon', 'daniel', 3, 27, 'free', E'*And the princes, governors, and captains, and the king''s counsellors, being gathered together, saw these men, upon whose bodies the fire had no power, nor was an hair of their head singed, neither were their coats changed, nor the smell of fire had passed on them.* (Daniel 3:27). *Quenched the violence of fire, escaped the edge of the sword, out of weakness were made strong* (Hebrews 11:34). The quenched violence of fire Hebrews names is this furnace: men *upon whose bodies the fire had no power.* They would not bow to the image, and a fourth *like the Son of Elohim* walked with them in the flames — faith that quenched the fire by refusing to deny their Elohim.'),
  ('canon', 'hebrews', 11, 35, 'canon', '1-kings', 17, 22, 'free', E'*And Yahuah (LORD) heard the voice of Elijah; and the soul of the child came into him again, and he revived.* (1 Kings 17:22). *Women received their dead raised to life again* (Hebrews 11:35). The first of the dead raised and restored to a woman is this child of the widow of Zarephath: *the soul of the child came into him again, and he revived.* The prophet stretched himself upon the child and Yahuah heard — the dead son given back alive to his mother.'),
  ('canon', 'hebrews', 11, 35, 'canon', '2-kings', 4, 35, 'free', E'*Then he returned, and walked in the house to and fro; and went up, and stretched himself upon him: and the child sneezed seven times, and the child opened his eyes.* (2 Kings 4:35). *Women received their dead raised to life again* (Hebrews 11:35). The Shunammite''s son is the second woman''s dead raised: *the child sneezed seven times, and the child opened his eyes.* Elisha shut the door and prayed and lay upon the dead boy, and the child was given back living — the raised dead Hebrews sets at the head of the witnesses'' afflictions.'),
  -- thread: hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees
  ('canon', 'hebrews', 11, 35, 'apocrypha', '2-maccabees', 7, 9, 'extras', E'*And when he was at the last gasp, he said, You like a fury takest us out of this present life, but the King of the world shall raise us up, who have died for his laws, to everlasting life.* (2 Maccabees 7:9). *and others were tortured, not accepting deliverance; that they might obtain a better resurrection* (Hebrews 11:35). Here is the witness the canon names only in summary, made flesh: the second of seven brothers, dying under torture rather than transgress, declaring *the King of the world shall raise us up, who have died for his laws, to everlasting life.* This is the *better resurrection* — chosen over the deliverance that would have cost them the law.'),
  ('canon', 'hebrews', 11, 35, 'apocrypha', '2-maccabees', 7, 11, 'extras', E'*And said courageously, These I had from heaven; and for his laws I despise them; and from him I hope to receive them again.* (2 Maccabees 7:11). *and others were tortured, not accepting deliverance; that they might obtain a better resurrection* (Hebrews 11:35). The third brother stretches out his tongue and his hands to be cut off, certain of the resurrection: *from him I hope to receive them again.* The torn body is surrendered in the hope of being raised whole — the very faith Hebrews crowns in the witnesses *not accepting deliverance.*'),
  ('canon', 'hebrews', 11, 35, 'apocrypha', '2-maccabees', 7, 14, 'extras', E'*So when he was ready to die he said thus, It is good, being put to death by men, to look for hope from Yahuah (God) to be raised up again by him: as for you, you shall have no resurrection to life.* (2 Maccabees 7:14). *and others were tortured, not accepting deliverance; that they might obtain a better resurrection* (Hebrews 11:35). The fourth brother names the two resurrections the framework holds — the faithful *raised up again,* the persecutor with *no resurrection to life.* He would rather be *put to death by men* and *look for hope from Yahuah* than escape; this is the better resurrection chosen over a bought deliverance.'),
  ('canon', 'hebrews', 11, 35, 'apocrypha', '2-maccabees', 7, 23, 'extras', E'*But doubtless the Creator of the world, who formed the generation of man, and found out the beginning of all things, will also of his own mercy give you breath and life again, as you now regard not your own selves for his laws'' sake.* (2 Maccabees 7:23). *and others were tortured, not accepting deliverance; that they might obtain a better resurrection* (Hebrews 11:35). The mother urges her sons to die by the same faith: the *Creator of the world... will also of his own mercy give you breath and life again.* She reasons from creation to resurrection — the One who first gave breath can give it again — and spends her seven sons on that hope rather than the law.'),
  ('canon', 'hebrews', 11, 35, 'apocrypha', '2-maccabees', 7, 29, 'extras', E'*Fear not this tormentor, but, being worthy of your brothers, take your death that I may receive you again in mercy with your brothers.* (2 Maccabees 7:29). *and others were tortured, not accepting deliverance; that they might obtain a better resurrection* (Hebrews 11:35). The mother''s last word to her youngest is the better resurrection in a sentence: *take your death that I may receive you again in mercy with your brothers.* Death accepted, deliverance refused, the reunion looked for past the grave — the faith of those of whom *the world was not worthy* (Hebrews 11:38).')
)
INSERT INTO cross_references (source_verse_id, target_verse_id, source, note, tier_required)
SELECT sv.verse_id, tv.verse_id, 'manual', i.note, i.tier::content_tier
  FROM input i
  JOIN _s222_h11_lookup sv ON sv.edition_slug=i.src_edition AND sv.book_slug=i.src_slug AND sv.chapter_number=i.src_ch AND sv.verse_number=i.src_v
  JOIN _s222_h11_lookup tv ON tv.edition_slug=i.tgt_edition AND tv.book_slug=i.tgt_slug AND tv.chapter_number=i.tgt_ch AND tv.verse_number=i.tgt_v
 WHERE sv.verse_id <> tv.verse_id
ON CONFLICT (source_verse_id, target_verse_id, source) DO NOTHING;

-- ----- threads -----
INSERT INTO cross_reference_threads (slug, title, summary_md, anchor_verse_id_start, anchor_verse_id_end, tier_required, sort_order)
SELECT th.slug, th.title, th.summary_md, sv.verse_id, ev.verse_id, th.tier_required::content_tier, th.sort_order
  FROM (VALUES
  ('hebrews-11-faith-the-substance-of-things-hoped-for-the-worlds-framed-genesis-1',
   E'Faith the Substance of Things Hoped For — the Worlds Framed by His Word (Genesis 1)',
   E'The chapter opens with the definition that governs every witness that follows: *Now faith is the substance of things hoped for, the evidence of things not seen* (Hebrews 11:1). The first thing faith lays hold of is the creation itself — *Through faith we understand that the worlds were framed by the word of Elohim (God), so that things which are seen were not made of things which do appear* (Hebrews 11:3). The Torah''s opening line is the first unseen-becoming-seen: *In the beginning Elohim (God) created the heaven and the earth* (Genesis 1:1), and *And Elohim (God) said, Let there be light: and there was light* (Genesis 1:3). The worlds had no maker but the word and no material but the speaking — the visible framed out of what does not appear. This is the ground of the whole cloud of witnesses: the unseen word of Elohim is the most substantial thing there is.',
   'free', 7971, 'hebrews', 11, 1, 3),
  ('hebrews-11-abel-a-more-excellent-sacrifice-genesis-4',
   E'Abel — a More Excellent Sacrifice, and Dead Yet Speaketh (Genesis 4)',
   E'The first named witness is the first man slain for his faith. *By faith Abel offered unto Elohim (God) a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, Elohim (God) testifying of his gifts: and by it he being dead yet speaketh* (Hebrews 11:4). The Torah shows the offering and the respect: *And Abel, he also brought of the firstlings of his flock and of the fat thereof. And Yahuah (LORD) had respect unto Abel and to his offering* (Genesis 4:4). Jubilees names it plainly — *Cain slew Abel because Elohim (God) accepted the sacrifice of Abel, and did not accept the offering of Cain* (Jubilees 4:2). And the dead man still speaks: *the voice of thy brother''s blood crieth unto me from the ground* (Genesis 4:10), which Jubilees hears as *his blood cried from the ground to heaven* (Jubilees 4:3). The righteous one slain for his offering is not silenced; his faith witnesses to every generation after him.',
   'extras', 7972, 'hebrews', 11, 4, 4),
  ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5',
   E'Enoch Translated That He Should Not See Death (Genesis 5; 1 Enoch; Jubilees; Sirach 44)',
   E'In a genealogy where every man ends *and he died,* one man does not. *By faith Enoch was translated that he should not see death; and was not found, because Elohim (God) had translated him: for before his translation he had this testimony, that he pleased Elohim (God)* (Hebrews 11:5). The Torah''s spare line is the seed: *And Enoch walked with Elohim (God): and he was not; for Elohim (God) took him* (Genesis 5:24). The restored library shows the taking from inside the vision — *my spirit was carried off and it ascended into the heavens: And I saw the holy sons of Elohim (God)* (1 Enoch 71:1), *he translated my spirit into the heaven of heavens* (1 Enoch 71:5) — and Jubilees names the removal: *he was taken from amongst the children of men, and we conducted him into the Garden of Eden in majesty and honour* (Jubilees 4:23). Ben Sira binds the two words Hebrews uses: *Enoch pleased Yahuah (God), and was translated, being an example of repentance to all generations* (Ecclesiasticus 44:16). And the writer draws the principle out: *without faith it is impossible to please him: for he that cometh to Elohim (God) must believe that he is, and that he is a rewarder of them that diligently seek him* (Hebrews 11:6). Enoch sought, and the reward of his seeking was to be taken to the One he sought, rather than left to death.',
   'extras', 7973, 'hebrews', 11, 5, 6),
  ('hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6',
   E'Noah — Warned of Things Not Seen, Prepared an Ark (Genesis 6; Sirach 44)',
   E'Faith acts on a word about a thing that has not yet appeared. *By faith Noah, being warned of Elohim (God) of things not seen as yet, moved with fear, prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith* (Hebrews 11:7). The warning was the announced flood — *And Elohim (God) said unto Noah, The end of all flesh is come before me; for the earth is filled with violence through them; and, behold, I will destroy them with the earth* (Genesis 6:13) — and the obedient action was the building: *Make thee an ark of gopher wood; rooms shalt thou make in the ark, and shalt pitch it within and without with pitch* (Genesis 6:14). The whole of Noah''s faith is one line of doing: *Thus did Noah; according to all that Elohim (God) commanded him, so did he* (Genesis 6:22). Ben Sira names the same righteousness and the office it carried: *Noah was found perfect and righteous; in the time of wrath he was taken in exchange for the world; therefore was he left as a remnant to the earth, when the flood came* (Ecclesiasticus 44:17). The ark is faith made visible — the substance of a thing hoped for, framed plank by plank against an unseen judgment.',
   'extras', 7974, 'hebrews', 11, 7, 7),
  ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22',
   E'Abraham Obeyed and Looked for a City — Sarah Received Strength — Isaac Offered (Genesis 12, 15, 18, 21, 22; Sirach 44)',
   E'The longest witness in the cloud is the friend of Elohim, whose whole life was faith walked out. *By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went* (Hebrews 11:8) — the call was *Get thee out of thy country, and from thy kindred, and from thy father''s house, unto a land that I will shew thee* (Genesis 12:1), a destination withheld and an inheritance unseen. He *looked for a city which hath foundations, whose builder and maker is Elohim (God)* (Hebrews 11:10). Sarah too: *Through faith also Sara herself received strength to conceive seed... because she judged him faithful who had promised* (Hebrews 11:11), believing the word at the tent door — *Is any thing too hard for Yahuah (LORD)?* (Genesis 18:14) — vindicated when *Sarah conceived, and bare Abraham a son in his old age, at the set time of which Elohim (God) had spoken* (Genesis 21:2). From the one man *as good as dead* sprang seed *as the stars of the sky in multitude* (Hebrews 11:12), the very star-promise of the night Yahuah brought him forth — *tell the stars... So shall thy seed be* (Genesis 15:5). And the trial: *By faith Abraham, when he was tried, offered up Isaac* (Hebrews 11:17), commanded *Take now thy son, thine only son Isaac, whom thou lovest... and offer him* (Genesis 22:2). Because the seed was promised through Isaac — and the oath stood, *in blessing I will bless thee, and in multiplying I will multiply thy seed as the stars of the heaven* (Genesis 22:17) — he reckoned *that Elohim (God) was able to raise him up, even from the dead* (Hebrews 11:19). Ben Sira names the proving: *when he was proved, he was found faithful* (Ecclesiasticus 44:20); and the oath: *exalt his seed as the stars* (Ecclesiasticus 44:21). Faith that is faithfulness reasoned its way to resurrection from an unbreakable promise.',
   'extras', 7975, 'hebrews', 11, 8, 19),
  ('hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50',
   E'The Patriarchs'' Blessing and the Bones of Joseph (Genesis 27, 48, 50)',
   E'Faith speaks over an unseen future and stakes even a burial on a promise. *By faith Isaac blessed Jacob and Esau concerning things to come* (Hebrews 11:20) — the dim-eyed patriarch reaching forward, *See, the smell of my son is as the smell of a field which Yahuah (LORD) hath blessed* (Genesis 27:27). *By faith Jacob, when he was a dying, blessed both the sons of Joseph; and worshipped, leaning upon the top of his staff* (Hebrews 11:21), naming over them *the Elohim (God), before whom my fathers Abraham and Isaac did walk* (Genesis 48:15) and *the Angel which redeemed me from all evil, bless the lads; and let my name be named on them* (Genesis 48:16) — the covenant set on the generation to come. *By faith Joseph, when he died, made mention of the departing of the children of Yashar''el (Israel); and gave commandment concerning his bones* (Hebrews 11:22): so sure of the visitation — *Elohim (God) will surely visit you, and bring you out of this land unto the land which he sware to Abraham, to Isaac, and to Jacob* (Genesis 50:24) — that he bound the people by oath, *ye shall carry up my bones from hence* (Genesis 50:25). Each blessed and commanded as though the unseen were already given.',
   'free', 7976, 'hebrews', 11, 20, 22),
  ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6',
   E'Moses Esteemed the Reproach of Messiah — the Passover, the Red Sea, Jericho, and Rahab (Exodus 2, 14; Joshua 2, 6)',
   E'Faith chooses the afflicted people of Elohim over the treasures of the world, and walks through walls of water and walls of stone. Moses was first kept by his parents'' faith — *when she saw him that he was a goodly child, she hid him three months* (Exodus 2:2) — *and they were not afraid of the king''s commandment* (Hebrews 11:23). Grown, *By faith Moses... refused to be called the son of Pharaoh''s daughter; Choosing rather to suffer affliction with the people of Elohim (God)* (Hebrews 11:24-25): *he went out unto his brethren, and looked on their burdens* (Exodus 2:11), *Esteeming the reproach of Messiah (Christ) greater riches than the treasures in Egypt* (Hebrews 11:26). *By faith they passed through the Red sea as by dry land: which the Egyptians assaying to do were drowned* (Hebrews 11:29) — *the children of Yashar''el (Israel) went into the midst of the sea upon the dry ground: and the waters were a wall unto them on their right hand, and on their left* (Exodus 14:22). *By faith the walls of Jericho fell down, after they were compassed about seven days* (Hebrews 11:30) — *the wall fell down flat, so that the people went up into the city* (Joshua 6:20). And the foreign woman who believed when her city would not: *By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace* (Hebrews 11:31), confessing *Yahuah Elohaychem (the LORD your God), he is Elohim (God) in heaven above, and in earth beneath* (Joshua 2:11), so that *Joshua saved Rahab the harlot alive... and she dwelleth in Yashar''el (Israel) even unto this day* (Joshua 6:25) — taken into the covenant people by her faith while the city perished.',
   'free', 7977, 'hebrews', 11, 23, 31),
  ('hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6',
   E'Stopped the Mouths of Lions and Quenched the Violence of Fire (Daniel 3, 6; 1 Kings 17; 2 Kings 4)',
   E'The summary of the prophets and the faithful is filled out by the deliverances the writer gestures at. *Who through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions* (Hebrews 11:33) — Daniel in the den: *My Elohim (God) hath sent his angel, and hath shut the lions'' mouths, that they have not hurt me* (Daniel 6:22), because he would not cease his prayer at the king''s decree. *Quenched the violence of fire, escaped the edge of the sword, out of weakness were made strong* (Hebrews 11:34) — the three in the furnace, *upon whose bodies the fire had no power, nor was an hair of their head singed* (Daniel 3:27), who would not bow to the image and walked unharmed with a fourth *like the Son of Elohim (God).* And the dead raised: *Women received their dead raised to life again* (Hebrews 11:35) — the widow of Zarephath''s son, *the soul of the child came into him again, and he revived* (1 Kings 17:22), and the Shunammite''s son, *the child sneezed seven times, and the child opened his eyes* (2 Kings 4:35). Faith subdued the lion, quenched the fire, and received back the dead.',
   'free', 7978, 'hebrews', 11, 32, 35),
  ('hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees',
   E'Tortured, Not Accepting Deliverance, That They Might Obtain a Better Resurrection — the Mother and Seven Sons (2 Maccabees 7)',
   E'The cloud darkens into the witnesses who were not delivered, and the restored library names them where the canon only summarizes: *and others were tortured, not accepting deliverance; that they might obtain a better resurrection* (Hebrews 11:35). These are the mother and her seven sons, who would die rather than transgress the law. The second declares, *the King of the world shall raise us up, who have died for his laws, to everlasting life* (2 Maccabees 7:9); the third stretches out his hands to be cut off — *from him I hope to receive them again* (2 Maccabees 7:11); the fourth names the two resurrections the framework holds, *to look for hope from Yahuah (God) to be raised up again by him: as for you, you shall have no resurrection to life* (2 Maccabees 7:14). The mother reasons from creation to resurrection: *the Creator of the world, who formed the generation of man... will also of his own mercy give you breath and life again* (2 Maccabees 7:23), and sends her youngest to die — *take your death that I may receive you again in mercy with your brothers* (2 Maccabees 7:29). They refused the deliverance that would have cost them the law, and looked for the better resurrection past the grave. These are they *of whom the world was not worthy* (Hebrews 11:38), who *received not the promise* in their lifetime because *Elohim (God) having provided some better thing for us, that they without us should not be made perfect* (Hebrews 11:40) — the faithful of every age waiting together for the one resurrection.',
   'extras', 7979, 'hebrews', 11, 35, 40)
  ) AS th(slug, title, summary_md, tier_required, sort_order, anchor_book, anchor_chapter, anchor_verse_start, anchor_verse_end)
  JOIN _s222_h11_lookup sv ON sv.edition_slug='canon' AND sv.book_slug=th.anchor_book AND sv.chapter_number=th.anchor_chapter AND sv.verse_number=th.anchor_verse_start
  JOIN _s222_h11_lookup ev ON ev.edition_slug='canon' AND ev.book_slug=th.anchor_book AND ev.chapter_number=th.anchor_chapter AND ev.verse_number=th.anchor_verse_end
ON CONFLICT (slug) DO NOTHING;

-- ----- thread_members -----
INSERT INTO cross_reference_thread_members (thread_id, cross_reference_id, sort_order, member_note)
SELECT t.id, cr.id, m.sort_order, m.member_note
  FROM (VALUES
    -- hebrews-11-faith-the-substance-of-things-hoped-for-the-worlds-framed-genesis-1
    ('hebrews-11-faith-the-substance-of-things-hoped-for-the-worlds-framed-genesis-1', 'canon','hebrews',11,3, 'canon','genesis',1,1, 1, E'*In the beginning Elohim (God) created the heaven and the earth* (Genesis 1:1) — the worlds *framed by the word of Elohim* (Hebrews 11:3), the first unseen made seen.'),
    ('hebrews-11-faith-the-substance-of-things-hoped-for-the-worlds-framed-genesis-1', 'canon','hebrews',11,3, 'canon','genesis',1,3, 2, E'*Let there be light: and there was light* (Genesis 1:3) — Elohim speaks and the unseen becomes evidence, the pattern faith lays hold of (Hebrews 11:1,3).'),
    -- hebrews-11-abel-a-more-excellent-sacrifice-genesis-4
    ('hebrews-11-abel-a-more-excellent-sacrifice-genesis-4', 'canon','hebrews',11,4, 'canon','genesis',4,4, 1, E'*Yahuah (LORD) had respect unto Abel and to his offering* (Genesis 4:4) — the respect is the *witness that he was righteous* (Hebrews 11:4).'),
    ('hebrews-11-abel-a-more-excellent-sacrifice-genesis-4', 'canon','hebrews',11,4, 'canon','genesis',4,10, 2, E'*The voice of thy brother''s blood crieth unto me from the ground* (Genesis 4:10) — the dead man who *yet speaketh* (Hebrews 11:4).'),
    ('hebrews-11-abel-a-more-excellent-sacrifice-genesis-4', 'canon','hebrews',11,4, 'jubilees','jubilees',4,2, 3, E'*Elohim (God) accepted the sacrifice of Abel, and did not accept the offering of Cain* (Jubilees 4:2) — the *more excellent sacrifice* named plainly (Hebrews 11:4).'),
    ('hebrews-11-abel-a-more-excellent-sacrifice-genesis-4', 'canon','hebrews',11,4, 'jubilees','jubilees',4,3, 4, E'*His blood cried from the ground to heaven* (Jubilees 4:3) — the slain witness still crying, *being dead yet speaketh* (Hebrews 11:4).'),
    -- hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5
    ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5', 'canon','hebrews',11,5, 'canon','genesis',5,24, 1, E'*And Enoch walked with Elohim (God): and he was not; for Elohim (God) took him* (Genesis 5:24) — *translated that he should not see death* (Hebrews 11:5).'),
    ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5', 'canon','hebrews',11,5, 'enoch','1-enoch',71,1, 2, E'*My spirit was carried off and it ascended into the heavens* (1 Enoch 71:1) — the taking shown from within, among *the holy sons of Elohim* (Hebrews 11:5).'),
    ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5', 'canon','hebrews',11,5, 'enoch','1-enoch',71,5, 3, E'*He translated my spirit into the heaven of heavens* (1 Enoch 71:5) — the very word Hebrews uses, *translated* (Hebrews 11:5).'),
    ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5', 'canon','hebrews',11,5, 'jubilees','jubilees',4,23, 4, E'*He was taken from amongst the children of men... in majesty and honour* (Jubilees 4:23) — the *was not found* of the Torah filled out (Hebrews 11:5).'),
    ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5', 'canon','hebrews',11,5, 'apocrypha','ecclesiasticus',44,16, 5, E'*Enoch pleased Yahuah (God), and was translated* (Ecclesiasticus 44:16) — the same two words, *pleased* and *translated* (Hebrews 11:5).'),
    ('hebrews-11-enoch-translated-that-he-should-not-see-death-genesis-5', 'canon','hebrews',11,6, 'canon','genesis',5,24, 6, E'*Enoch walked with Elohim (God)* (Genesis 5:24) — the proof that *without faith it is impossible to please him* (Hebrews 11:6).'),
    -- hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6
    ('hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6', 'canon','hebrews',11,7, 'canon','genesis',6,13, 1, E'*The end of all flesh is come before me* (Genesis 6:13) — the warning of *things not seen as yet* (Hebrews 11:7).'),
    ('hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6', 'canon','hebrews',11,7, 'canon','genesis',6,14, 2, E'*Make thee an ark of gopher wood* (Genesis 6:14) — the obedient action, the ark *prepared to the saving of his house* (Hebrews 11:7).'),
    ('hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6', 'canon','hebrews',11,7, 'canon','genesis',6,22, 3, E'*According to all that Elohim (God) commanded him, so did he* (Genesis 6:22) — the *righteousness which is by faith* (Hebrews 11:7).'),
    ('hebrews-11-noah-warned-of-things-not-seen-prepared-an-ark-genesis-6', 'canon','hebrews',11,7, 'apocrypha','ecclesiasticus',44,17, 4, E'*Noah was found perfect and righteous... left as a remnant to the earth* (Ecclesiasticus 44:17) — the heir of righteousness preserved through the wrath (Hebrews 11:7).'),
    -- hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,8, 'canon','genesis',12,1, 1, E'*Get thee out of thy country... unto a land that I will shew thee* (Genesis 12:1) — Abraham *obeyed; and he went out, not knowing whither he went* (Hebrews 11:8).'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,11, 'canon','genesis',18,14, 2, E'*Is any thing too hard for Yahuah (LORD)?* (Genesis 18:14) — the promise Sarah *judged him faithful who had promised* (Hebrews 11:11).'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,11, 'canon','genesis',21,2, 3, E'*Sarah conceived, and bare Abraham a son in his old age, at the set time* (Genesis 21:2) — the faith vindicated, strength *to conceive seed* (Hebrews 11:11).'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,12, 'canon','genesis',15,5, 4, E'*Tell the stars, if thou be able to number them... So shall thy seed be* (Genesis 15:5) — the seed *as the stars of the sky in multitude* (Hebrews 11:12).'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,17, 'canon','genesis',22,2, 5, E'*Take now thy son, thine only son Isaac... and offer him* (Genesis 22:2) — the trial in which Abraham *offered up Isaac* (Hebrews 11:17).'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,18, 'canon','genesis',22,17, 6, E'*In blessing I will bless thee, and in multiplying I will multiply thy seed* (Genesis 22:17) — the oath behind *that in Isaac shall thy seed be called* (Hebrews 11:18).'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,17, 'apocrypha','ecclesiasticus',44,20, 7, E'*When he was proved, he was found faithful* (Ecclesiasticus 44:20) — Abraham *when he was tried* (Hebrews 11:17), faith that is faithfulness.'),
    ('hebrews-11-abraham-looked-for-a-city-and-offered-isaac-genesis-12-22', 'canon','hebrews',11,12, 'apocrypha','ecclesiasticus',44,21, 8, E'*Exalt his seed as the stars* (Ecclesiasticus 44:21) — the oath behind the seed *so many as the stars of the sky* (Hebrews 11:12).'),
    -- hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50
    ('hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50', 'canon','hebrews',11,20, 'canon','genesis',27,27, 1, E'*The smell of my son is as the smell of a field which Yahuah (LORD) hath blessed* (Genesis 27:27) — Isaac *blessed Jacob and Esau concerning things to come* (Hebrews 11:20).'),
    ('hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50', 'canon','hebrews',11,21, 'canon','genesis',48,15, 2, E'*Elohim (God), before whom my fathers Abraham and Isaac did walk* (Genesis 48:15) — the dying Jacob *blessed both the sons of Joseph* (Hebrews 11:21).'),
    ('hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50', 'canon','hebrews',11,21, 'canon','genesis',48,16, 3, E'*Let my name be named on them, and the name of my fathers Abraham and Isaac* (Genesis 48:16) — the covenant set on the lads by faith (Hebrews 11:21).'),
    ('hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50', 'canon','hebrews',11,22, 'canon','genesis',50,24, 4, E'*Elohim (God) will surely visit you, and bring you out of this land* (Genesis 50:24) — Joseph''s *mention of the departing of the children of Yashar''el* (Hebrews 11:22).'),
    ('hebrews-11-the-patriarchs-blessing-and-the-bones-of-joseph-genesis-27-48-50', 'canon','hebrews',11,22, 'canon','genesis',50,25, 5, E'*Ye shall carry up my bones from hence* (Genesis 50:25) — the *commandment concerning his bones* (Hebrews 11:22), faith staking his burial on the oath.'),
    -- hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6
    ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6', 'canon','hebrews',11,23, 'canon','exodus',2,2, 1, E'*She hid him three months* (Exodus 2:2) — Moses *hid three months of his parents... not afraid of the king''s commandment* (Hebrews 11:23).'),
    ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6', 'canon','hebrews',11,24, 'canon','exodus',2,11, 2, E'*He went out unto his brethren, and looked on their burdens* (Exodus 2:11) — Moses *refused to be called the son of Pharaoh''s daughter* (Hebrews 11:24).'),
    ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6', 'canon','hebrews',11,29, 'canon','exodus',14,22, 3, E'*The waters were a wall unto them on their right hand, and on their left* (Exodus 14:22) — they *passed through the Red sea as by dry land* (Hebrews 11:29).'),
    ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6', 'canon','hebrews',11,30, 'canon','joshua',6,20, 4, E'*The wall fell down flat* (Joshua 6:20) — *the walls of Jericho fell down, after they were compassed about seven days* (Hebrews 11:30).'),
    ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6', 'canon','hebrews',11,31, 'canon','joshua',2,11, 5, E'*Yahuah Elohaychem (the LORD your God), he is Elohim (God) in heaven above, and in earth beneath* (Joshua 2:11) — Rahab''s faith while the city *believed not* (Hebrews 11:31).'),
    ('hebrews-11-moses-the-reproach-of-messiah-the-passover-jericho-and-rahab-exodus-2-joshua-2-6', 'canon','hebrews',11,31, 'canon','joshua',6,25, 6, E'*Joshua saved Rahab the harlot alive... she dwelleth in Yashar''el (Israel) even unto this day* (Joshua 6:25) — she *perished not with them that believed not* (Hebrews 11:31).'),
    -- hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6
    ('hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6', 'canon','hebrews',11,33, 'canon','daniel',6,22, 1, E'*My Elohim (God) hath sent his angel, and hath shut the lions'' mouths* (Daniel 6:22) — through faith they *stopped the mouths of lions* (Hebrews 11:33).'),
    ('hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6', 'canon','hebrews',11,34, 'canon','daniel',3,27, 2, E'*The fire had no power, nor was an hair of their head singed* (Daniel 3:27) — they *quenched the violence of fire* (Hebrews 11:34).'),
    ('hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6', 'canon','hebrews',11,35, 'canon','1-kings',17,22, 3, E'*The soul of the child came into him again, and he revived* (1 Kings 17:22) — *women received their dead raised to life again* (Hebrews 11:35).'),
    ('hebrews-11-stopped-the-mouths-of-lions-and-quenched-the-violence-of-fire-daniel-3-6', 'canon','hebrews',11,35, 'canon','2-kings',4,35, 4, E'*The child sneezed seven times, and the child opened his eyes* (2 Kings 4:35) — the Shunammite''s dead son raised (Hebrews 11:35).'),
    -- hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees
    ('hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees', 'canon','hebrews',11,35, 'apocrypha','2-maccabees',7,9, 1, E'*The King of the world shall raise us up, who have died for his laws, to everlasting life* (2 Maccabees 7:9) — the *better resurrection* chosen over deliverance (Hebrews 11:35).'),
    ('hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees', 'canon','hebrews',11,35, 'apocrypha','2-maccabees',7,11, 2, E'*From him I hope to receive them again* (2 Maccabees 7:11) — the torn body surrendered in the hope of being raised whole (Hebrews 11:35).'),
    ('hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees', 'canon','hebrews',11,35, 'apocrypha','2-maccabees',7,14, 3, E'*Raised up again by him: as for you, you shall have no resurrection to life* (2 Maccabees 7:14) — the two resurrections named, the *better* one looked for (Hebrews 11:35).'),
    ('hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees', 'canon','hebrews',11,35, 'apocrypha','2-maccabees',7,23, 4, E'*The Creator of the world... will also of his own mercy give you breath and life again* (2 Maccabees 7:23) — the mother reasons from creation to resurrection (Hebrews 11:35).'),
    ('hebrews-11-tortured-for-a-better-resurrection-the-mother-and-seven-sons-2-maccabees', 'canon','hebrews',11,35, 'apocrypha','2-maccabees',7,29, 5, E'*Take your death that I may receive you again in mercy with your brothers* (2 Maccabees 7:29) — the reunion past the grave, *not accepting deliverance* (Hebrews 11:35).')
  ) AS m(thread_slug, src_edition, src_slug, src_ch, src_v, tgt_edition, tgt_slug, tgt_ch, tgt_v, sort_order, member_note)
  JOIN cross_reference_threads t ON t.slug = m.thread_slug
  JOIN _s222_h11_lookup sv ON sv.edition_slug=m.src_edition AND sv.book_slug=m.src_slug AND sv.chapter_number=m.src_ch AND sv.verse_number=m.src_v
  JOIN _s222_h11_lookup tv ON tv.edition_slug=m.tgt_edition AND tv.book_slug=m.tgt_slug AND tv.chapter_number=m.tgt_ch AND tv.verse_number=m.tgt_v
  JOIN cross_references cr ON cr.source_verse_id=sv.verse_id AND cr.target_verse_id=tv.verse_id AND cr.source='manual'
ON CONFLICT (thread_id, cross_reference_id) DO NOTHING;
