-- ----- fragment: minion_3john_01.sql (S244 3 John) -----
-- =====================================================================
-- S244 minion — 3 JOHN 1 FULL-LIBRARY cross-references
-- =====================================================================
-- Book: 3 JOHN (Yochanan Gimel), one chapter, 14 verses. Tag: t244.
-- Temp view: _s244_3john_lookup. Sort band: floor 10180, step 3 (10180, 10183, 10186).
-- Source is ALWAYS the canon 3-john verse; targets span Tanakh + extras + NT, woven.
-- Tiers per-row: canon target = 'free'; extra-canonical target = 'extras'.
--
-- GOVERNING FRAME: 3 John is the least Tanakh-saturated book in the canon — a short, personal
-- letter (Gaius, Diotrephes, Demetrius). Its framework center is THE TWO-WAYS TEST: he that doeth
-- good is of Elohim, he that doeth evil hath not seen Elohim (v.11). Conduct — doing good, walking
-- in truth, loving the stranger — is the evidentiary proof of belonging to Yahuah, the same
-- master-filter as 1 John. No replacement theology, no law-vs-grace antithesis. The Torah's
-- good-and-evil and love-the-stranger are the standard.
--
-- 3 John coverage:
--   v.1   Tanakh / Extras / NT: none warranted (greeting to Gaius — love in the truth)
--   v.2   Tanakh / Extras / NT: none warranted (wish for health/prosperity — personal)
--   v.3   Tanakh: Psalm 86:11; Psalm 119:1; 1 Kings 2:4; 2 Kings 20:3 / NT: 2 John 4  [walking-in-truth]
--   v.4   Tanakh: (walk in truth, carried by v.3 thread) / NT: 2 John 4  [walking-in-truth]
--   v.5   Tanakh: Genesis 18:1-8; Leviticus 19:34; Deuteronomy 10:18-19; Isaiah 58:7 / Extras: Tobit 4:16; Sirach 7:32 / NT: Matthew 25:35; Hebrews 13:2; Romans 12:13  [receiving-the-brethren]
--   v.6   Tanakh: (hospitality, carried by v.5 thread)  [receiving-the-brethren]
--   v.7   Tanakh / Extras / NT: none warranted (for his name's sake — pastoral note)
--   v.8   Tanakh: (fellowhelpers, carried by v.5 thread)  [receiving-the-brethren]
--   v.9   Tanakh / Extras / NT: none warranted (Diotrephes — personal pastoral matter)
--   v.10  Tanakh / Extras / NT: none warranted (Diotrephes' deeds — personal pastoral matter)
--   v.11  Tanakh: Psalm 34:14; Psalm 37:27; Isaiah 1:16-17; Amos 5:14-15; Proverbs 3:7; Deuteronomy 30:15 / NT: 1 John 3:7,10  [TWO-WAYS TEST ★★]
--   v.12  Tanakh / Extras / NT: none warranted (Demetrius' good report — personal)
--   v.13  Tanakh / Extras / NT: none warranted (greeting — many things to write)
--   v.14  Tanakh / Extras / NT: none warranted (greeting — peace, salute the friends)
--
-- Threads (3):
--   1. 3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1  [★★ v.11, free, 10180]
--   2. 3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2  [v.3-4, free, 10183]
--   3. 3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10  [v.5-8, extras, 10186]
-- =====================================================================

CREATE TEMP VIEW _s244_3john_lookup AS
SELECT e.slug AS edition_slug, b.slug AS book_slug, c.chapter_number, v.verse_number, v.id AS verse_id
  FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
  JOIN editions e ON b.edition_id = e.id
 WHERE e.slug IN ('canon','enoch','jubilees','jasher','apocrypha','apocrypha-charles-vol1','pseudepigrapha','adam-eve-conflict','apocalypse-of-abraham','ascension-isaiah','sonnini-acts-29');

WITH input(src_edition, src_slug, src_ch, src_v,
           tgt_edition, tgt_slug, tgt_ch, tgt_v, tier, note) AS (VALUES
  -- thread: 3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1  [★★ TWO-WAYS TEST]
  ('canon', '3-john', 1, 11, 'canon', 'psalms', 34, 14, 'free', E'*Depart from evil, and do good; seek peace, and pursue it.* (Psalm 34:14). The Two-Ways charge is ancient: turn from the evil, do the good. John writes the same test as the proof of belonging — *follow not that which is evil, but that which is good. He that doeth good is of Elohim (God)* (3 John 11). The departing-from-evil and doing-good of David''s psalm is the very conduct by which John says a man is shown to be of Yahuah (LORD).'),
  ('canon', '3-john', 1, 11, 'canon', 'psalms', 37, 27, 'free', E'*Depart from evil, and do good; and dwell for evermore.* (Psalm 37:27). The psalm joins the doing of good to abiding for ever — and John joins it to belonging to Elohim (God): *He that doeth good is of Elohim (God): but he that doeth evil hath not seen Elohim (God)* (3 John 11). The two ways are set side by side in both texts; the one who departs from evil and does good is the one who dwells with Yahuah (LORD) for evermore.'),
  ('canon', '3-john', 1, 11, 'canon', 'isaiah', 1, 16, 'free', E'*Wash you, make you clean; put away the evil of your doings from before mine eyes; cease to do evil;* (Isaiah 1:16). Yahuah (LORD) sets the first half of the test: *cease to do evil.* John says *follow not that which is evil* (3 John 11). The prophet''s call to put away the evil of the doings is the negative side of the Two-Ways proof — conduct, not profession, is what Yahuah (LORD) weighs.'),
  ('canon', '3-john', 1, 11, 'canon', 'isaiah', 1, 17, 'free', E'*Learn to do well; seek judgment, relieve the oppressed, judge the fatherless, plead for the widow.* (Isaiah 1:17). And the second half: *learn to do well.* John says *but that which is good. He that doeth good is of Elohim (God)* (3 John 11). The prophet fills out the doing of good with justice to the oppressed, the fatherless, the widow — the good that Yahuah (LORD) requires is no abstraction but the deeds of mercy and righteousness by which a man is shown to be His.'),
  ('canon', '3-john', 1, 11, 'canon', 'amos', 5, 14, 'free', E'*Seek good, and not evil, that ye may live: and so Yahuah (LORD), the Elohim (God) of hosts, shall be with you, as ye have spoken.* (Amos 5:14). Amos ties seeking good to life and to Yahuah''s (LORD''s) presence — *that ye may live... shall be with you.* John ties doing good to belonging: *He that doeth good is of Elohim (God)* (3 John 11). To seek the good and not the evil is the way of life, the way of the One who is with His people; the deed proves the heart.'),
  ('canon', '3-john', 1, 11, 'canon', 'amos', 5, 15, 'free', E'*Hate the evil, and love the good, and establish judgment in the gate: it may be that Yahuah Elohim (the LORD God) of hosts will be gracious unto the remnant of Joseph.* (Amos 5:15). The prophet sharpens the test into the affections: *hate the evil, and love the good.* John''s *follow not that which is evil, but that which is good* (3 John 11) is the same disposition — not a neutral leaning but a love of the good and a hatred of the evil, the mark of the remnant Yahuah (LORD) preserves.'),
  ('canon', '3-john', 1, 11, 'canon', 'proverbs', 3, 7, 'free', E'*Be not wise in thine own eyes: fear Yahuah (LORD), and depart from evil.* (Proverbs 3:7). Wisdom binds the fear of Yahuah (LORD) to departing from evil. John binds belonging to Elohim (God) to the same turning: *follow not that which is evil... but he that doeth evil hath not seen Elohim (God)* (3 John 11). To fear Yahuah (LORD) and to depart from evil are one motion; the man who does evil shows he has not seen Him.'),
  ('canon', '3-john', 1, 11, 'canon', 'deuteronomy', 30, 15, 'free', E'*See, I have set before thee this day life and good, and death and evil;* (Deuteronomy 30:15). Here is the Two Ways at their root — Yahuah (LORD) sets before Yashar''el (Israel) *life and good, and death and evil.* John''s test stands directly upon it: *follow not that which is evil, but that which is good* (3 John 11). The choice Moses set before the people is the choice in every deed; to do the good is to choose life and to be of Elohim (God), to do the evil is to choose death and to show one has not seen Him.'),
  ('canon', '3-john', 1, 11, 'canon', '1-john', 3, 7, 'free', E'*Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous.* (1 John 3:7). John''s first letter speaks the same evidentiary test, almost word for word: the doing is the proof — *he that doeth righteousness is righteous.* So in the third letter, *He that doeth good is of Elohim (God)* (3 John 11). One mind, one master-filter: a man is known not by his claim but by his conduct.'),
  ('canon', '3-john', 1, 11, 'canon', '1-john', 3, 10, 'free', E'*In this the children of Elohim (God) are manifest, and the children of the devil: whosoever doeth not righteousness is not of Elohim (God), neither he that loveth not his brother.* (1 John 3:10). The first letter draws the line exactly where the third draws it: the deed makes manifest whose children men are — *whosoever doeth not righteousness is not of Elohim (God).* So *he that doeth evil hath not seen Elohim (God)* (3 John 11). Doing good and loving the brother are the marks of the children of Elohim (God); the Two Ways divide the family of light from the family of darkness.'),
  -- thread: 3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2
  ('canon', '3-john', 1, 3, 'canon', 'psalms', 86, 11, 'free', E'*Teach me thy way, O Yahuah (LORD); I will walk in thy truth: unite my heart to fear thy name.* (Psalm 86:11). To walk in the truth is a Tanakh path long before it is John''s joy. David prays *I will walk in thy truth,* and John rejoices that Gaius does so — *thou walkest in the truth* (3 John 3). The truth walked in is Yahuah''s (LORD''s) own way, taught to the heart that fears His name.'),
  ('canon', '3-john', 1, 3, 'canon', 'psalms', 119, 1, 'free', E'*Blessed are the undefiled in the way, who walk in the law of Yahuah (LORD).* (Psalm 119:1). The psalm names the blessing of those who *walk in the law of Yahuah (LORD)* — and to walk in the truth is to walk in His law, His way unblemished. John''s rejoicing that the brethren *testified of the truth that is in thee, even as thou walkest in the truth* (3 John 3) is rejoicing over this very walk: the undefiled way of Yahuah''s (LORD''s) Torah.'),
  ('canon', '3-john', 1, 3, 'canon', '1-kings', 2, 4, 'free', E'*That Yahuah (LORD) may continue his word which he spake concerning me, saying, If thy children take heed to their way, to walk before me in truth with all their heart and with all their soul, there shall not fail thee (said he) a man on the throne of Yashar''el (Israel).* (1 Kings 2:4). David''s charge to Solomon makes walking in truth the covenant condition: *to walk before me in truth with all their heart.* John''s joy that his children *walk in truth* (3 John 4) is the joy of that same covenant fidelity — to walk before Yahuah (LORD) in truth with the whole heart.'),
  ('canon', '3-john', 1, 3, 'canon', '2-kings', 20, 3, 'free', E'*I beseech thee, O Yahuah (LORD), remember now how I have walked before thee in truth and with a perfect heart, and have done that which is good in thy sight. And Hezekiah wept sore.* (2 Kings 20:3). Hezekiah pleads his walk before Yahuah (LORD) *in truth and with a perfect heart, and have done that which is good in thy sight* — joining, in one breath, walking in truth and doing good, the two notes of this whole letter. John''s greatest joy is to hear his children *walk in truth* (3 John 4), the very walk Hezekiah pleaded.'),
  ('canon', '3-john', 1, 3, 'canon', '2-john', 1, 4, 'free', E'*I rejoiced greatly that I found of thy children walking in truth, as we have received a commandment from the Father.* (2 John 4). The sister-letter opens with the identical joy and the identical phrase: *I rejoiced greatly that I found of thy children walking in truth.* So here: *I rejoiced greatly, when the brethren came and testified of the truth that is in thee, even as thou walkest in the truth* (3 John 3). One elder, one heart — and the walking in truth is *as we have received a commandment from the Father,* truth that is kept, not merely held.'),
  -- thread: 3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10
  ('canon', '3-john', 1, 5, 'canon', 'genesis', 18, 1, 'free', E'*And Yahuah (LORD) appeared unto him in the plains of Mamre: and he sat in the tent door in the heat of the day;* (Genesis 18:1). The pattern of receiving the sent ones begins with Abraham at the tent door, where Yahuah (LORD) appeared in the heat of the day. John praises Gaius for what Abraham first did — receiving travellers faithfully: *thou doest faithfully whatsoever thou doest to the brethren, and to strangers* (3 John 5).'),
  ('canon', '3-john', 1, 5, 'canon', 'genesis', 18, 2, 'free', E'*And he lift up his eyes and looked, and, lo, three men stood by him: and when he saw them, he ran to meet them from the tent door, and bowed himself toward the ground,* (Genesis 18:2). Abraham *ran to meet them* — the haste of true hospitality to the stranger. John commends the same eager welcome of the brethren and strangers (3 John 5); the three men Abraham ran to receive were messengers of Yahuah (LORD), and to receive the sent is to receive the One who sent them.'),
  ('canon', '3-john', 1, 5, 'canon', 'genesis', 18, 8, 'free', E'*And he took butter, and milk, and the calf which he had dressed, and set it before them; and he stood by them under the tree, and they did eat.* (Genesis 18:8). Abraham sets the meal before his guests and stands to serve them. This faithful service to the travelling stranger is exactly what John means: *thou doest faithfully whatsoever thou doest to the brethren, and to strangers* (3 John 5), bringing them *forward on their journey after a godly sort* (3 John 6).'),
  ('canon', '3-john', 1, 5, 'canon', 'leviticus', 19, 34, 'free', E'*But the stranger that dwelleth with you shall be unto you as one born among you, and thou shalt love him as thyself; for ye were strangers in the land of Egypt: I am Yahuah Elohaychem (the LORD your God).* (Leviticus 19:34). The Torah commands love of the stranger as of oneself — the very law beneath Gaius'' faithfulness *to the brethren, and to strangers* (3 John 5). Receiving the sent ones is not a new ethic but the keeping of Leviticus 19: the stranger loved as one born among you, because Yahuah (LORD) is your Elohim (God).'),
  ('canon', '3-john', 1, 5, 'canon', 'deuteronomy', 10, 18, 'free', E'*He doth execute the judgment of the fatherless and widow, and loveth the stranger, in giving him food and raiment.* (Deuteronomy 10:18). Yahuah (LORD) Himself *loveth the stranger, in giving him food and raiment* — and those who are His imitate Him. Gaius'' giving to the brethren and strangers (3 John 5) is a walking in Yahuah''s (LORD''s) own way, who feeds and clothes the sojourner.'),
  ('canon', '3-john', 1, 5, 'canon', 'deuteronomy', 10, 19, 'free', E'*Love ye therefore the stranger: for ye were strangers in the land of Egypt.* (Deuteronomy 10:19). The command is plain and grounded in Yashar''el''s (Israel''s) own memory: *love ye therefore the stranger.* John''s commendation of faithfulness *to the brethren, and to strangers* (3 John 5) is obedience to this word; the people once strangers in Egypt are to love the stranger now.'),
  ('canon', '3-john', 1, 5, 'canon', 'isaiah', 58, 7, 'free', E'*Is it not to deal thy bread to the hungry, and that thou bring the poor that are cast out to thy house? when thou seest the naked, that thou cover him; and that thou hide not thyself from thine own flesh?* (Isaiah 58:7). The fast Yahuah (LORD) chooses is to bring the cast-out poor to one''s house and feed the hungry — the open door John praises. To receive the brethren so that *we might be fellowhelpers to the truth* (3 John 8) is to keep Isaiah''s fast: bread to the hungry, shelter to the homeless, hiding not oneself from one''s own flesh.'),
  ('canon', '3-john', 1, 5, 'apocrypha', 'tobit', 4, 16, 'extras', E'*Give of your bread to the hungry, and of your garments to them that are naked; and according to your abundance give alms: and let not your eye be envious, when you give alms.* (Tobit 4:16). Tobit charges his son to *give of your bread to the hungry, and of your garments to them that are naked* — the household ethic of charity John commends in Gaius'' care *to the brethren, and to strangers* (3 John 5). The restored library teaches the same hospitality the Torah commands and Isaiah requires.'),
  ('canon', '3-john', 1, 5, 'apocrypha', 'ecclesiasticus', 7, 32, 'extras', E'*And stretch yours hand to the poor, that your blessing may be perfected.* (Sirach 7:32). Ben Sira: *stretch yours hand to the poor, that your blessing may be perfected* — the giving by which a blessing is completed. John commends Gaius for doing faithfully whatever he does *to the brethren, and to strangers* (3 John 5); the open hand to the needy is the perfecting of the blessing, the fellowship that makes one a fellowhelper to the truth.'),
  ('canon', '3-john', 1, 5, 'canon', 'matthew', 25, 35, 'free', E'*For I was an hungred, and ye gave me meat: I was thirsty, and ye gave me drink: I was a stranger, and ye took me in:* (Matthew 25:35). Yahusha (Jesus) makes receiving the stranger a receiving of Himself: *I was a stranger, and ye took me in.* John praises exactly this in Gaius — faithfulness *to the brethren, and to strangers* (3 John 5). To take in the sent ones is, in the King''s own reckoning, to take in the King.'),
  ('canon', '3-john', 1, 5, 'canon', 'hebrews', 13, 2, 'free', E'*Be not forgetful to entertain strangers: for thereby some have entertained angels unawares.* (Hebrews 13:2). The exhortation looks straight back to Abraham at Mamre: *some have entertained angels unawares.* John commends the same — receiving *the brethren, and to strangers* (3 John 5). The host of the sent ones may, as Abraham did, be hosting the messengers of Yahuah (LORD); hospitality to the stranger is no small thing.'),
  ('canon', '3-john', 1, 5, 'canon', 'romans', 12, 13, 'free', E'*Distributing to the necessity of saints; given to hospitality.* (Romans 12:13). Paul names the same duty John praises: *given to hospitality,* distributing to the saints'' need. Gaius is the very pattern — faithful *to the brethren, and to strangers* (3 John 5), bringing them forward on their journey, that all may be *fellowhelpers to the truth* (3 John 8).')
)
INSERT INTO cross_references (source_verse_id, target_verse_id, source, note, tier_required)
SELECT sv.verse_id, tv.verse_id, 'manual', i.note, i.tier::content_tier
  FROM input i
  JOIN _s244_3john_lookup sv ON sv.edition_slug=i.src_edition AND sv.book_slug=i.src_slug AND sv.chapter_number=i.src_ch AND sv.verse_number=i.src_v
  JOIN _s244_3john_lookup tv ON tv.edition_slug=i.tgt_edition AND tv.book_slug=i.tgt_slug AND tv.chapter_number=i.tgt_ch AND tv.verse_number=i.tgt_v
 WHERE sv.verse_id <> tv.verse_id
ON CONFLICT (source_verse_id, target_verse_id, source) DO NOTHING;

-- ----- threads -----
INSERT INTO cross_reference_threads (slug, title, summary_md, anchor_verse_id_start, anchor_verse_id_end, tier_required, sort_order)
SELECT '3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1',
       E'Follow not evil but good — he that doeth good is of Elohim: the Two-Ways test (Psalm 34, 37; Isaiah 1; Amos 5)',
       E'The framework center of the whole letter stands here: *Beloved, follow not that which is evil, but that which is good. He that doeth good is of Elohim (God): but he that doeth evil hath not seen Elohim (God)* (3 John 11). This is the Two-Ways test — conduct is the proof of belonging to Yahuah (LORD), the same evidentiary master-filter as John''s first letter, where knowing Him is shown by the deed. The two ways are set at the very root of the Torah: *See, I have set before thee this day life and good, and death and evil* (Deuteronomy 30:15) — the choice in every deed. The Psalms carry the charge twice over: *Depart from evil, and do good; seek peace, and pursue it* (Psalm 34:14), and *Depart from evil, and do good; and dwell for evermore* (Psalm 37:27), binding the doing of good to abiding with Yahuah (LORD) for ever. Isaiah gives both halves of the test in order — *cease to do evil; learn to do well* (Isaiah 1:16-17), filling out the good with justice to the oppressed, the fatherless, the widow. Amos sharpens it into the affections and joins it to life and to Yahuah''s (LORD''s) presence: *Seek good, and not evil, that ye may live... Hate the evil, and love the good* (Amos 5:14-15). And wisdom binds it to the fear of Yahuah (LORD): *fear Yahuah (LORD), and depart from evil* (Proverbs 3:7). John''s own first letter speaks the test almost word for word — *he that doeth righteousness is righteous* (1 John 3:7), and *whosoever doeth not righteousness is not of Elohim (God), neither he that loveth not his brother* (1 John 3:10): the deed makes manifest whose children men are. There is no replacement here and no law-against-grace: doing good and turning from evil is the Torah''s own measure, the standard by which a man is shown to be of Elohim (God). Conduct is the proof.',
       sv.verse_id, ev.verse_id, 'free', 10180
  FROM _s244_3john_lookup sv, _s244_3john_lookup ev
 WHERE sv.edition_slug='canon' AND sv.book_slug='3-john' AND sv.chapter_number=1 AND sv.verse_number=11
   AND ev.edition_slug='canon' AND ev.book_slug='3-john' AND ev.chapter_number=1 AND ev.verse_number=11
ON CONFLICT (slug) DO NOTHING;

INSERT INTO cross_reference_threads (slug, title, summary_md, anchor_verse_id_start, anchor_verse_id_end, tier_required, sort_order)
SELECT '3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2',
       E'Walking in the truth (Psalm 86, 119; 1 Kings 2; 2 Kings 20)',
       E'John''s joy over Gaius is a Tanakh joy: *I rejoiced greatly, when the brethren came and testified of the truth that is in thee, even as thou walkest in the truth. I have no greater joy than to hear that my children walk in truth* (3 John 3-4). To walk in the truth is an ancient path. David prays it: *Teach me thy way, O Yahuah (LORD); I will walk in thy truth: unite my heart to fear thy name* (Psalm 86:11). The long psalm of the Torah names its blessing: *Blessed are the undefiled in the way, who walk in the law of Yahuah (LORD)* (Psalm 119:1) — for to walk in the truth is to walk in His law, His undefiled way. It is the covenant condition David charged upon Solomon: *to walk before me in truth with all their heart and with all their soul* (1 Kings 2:4); and the plea Hezekiah made on his bed: *remember now how I have walked before thee in truth and with a perfect heart, and have done that which is good in thy sight* (2 Kings 20:3) — joining, in one breath, walking in truth and doing good, the two notes of this whole letter. And the sister-letter opens with the identical phrase and the identical joy: *I rejoiced greatly that I found of thy children walking in truth, as we have received a commandment from the Father* (2 John 4). The truth walked in is Yahuah''s (LORD''s) own way, kept with the whole heart — not merely held, but done.',
       sv.verse_id, ev.verse_id, 'free', 10183
  FROM _s244_3john_lookup sv, _s244_3john_lookup ev
 WHERE sv.edition_slug='canon' AND sv.book_slug='3-john' AND sv.chapter_number=1 AND sv.verse_number=3
   AND ev.edition_slug='canon' AND ev.book_slug='3-john' AND ev.chapter_number=1 AND ev.verse_number=4
ON CONFLICT (slug) DO NOTHING;

INSERT INTO cross_reference_threads (slug, title, summary_md, anchor_verse_id_start, anchor_verse_id_end, tier_required, sort_order)
SELECT '3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10',
       E'Receiving the brethren, fellowhelpers to the truth — love the stranger (Genesis 18; Leviticus 19; Deuteronomy 10; Isaiah 58)',
       E'John praises Gaius for the open door: *Beloved, thou doest faithfully whatsoever thou doest to the brethren, and to strangers... We therefore ought to receive such, that we might be fellowhelpers to the truth* (3 John 5,8). The receiving of the sent ones is no new ethic but the keeping of the Torah''s love-the-stranger. The pattern begins with Abraham at the tent door: *And he lift up his eyes and looked, and, lo, three men stood by him: and when he saw them, he ran to meet them from the tent door* (Genesis 18:2), setting butter and milk and the dressed calf before them (Genesis 18:8) — and *thereby some have entertained angels unawares* (Hebrews 13:2). The law commands it outright: *the stranger that dwelleth with you shall be unto you as one born among you, and thou shalt love him as thyself; for ye were strangers in the land of Egypt* (Leviticus 19:34); and again, *Love ye therefore the stranger: for ye were strangers in the land of Egypt* (Deuteronomy 10:19) — for Yahuah (LORD) Himself *loveth the stranger, in giving him food and raiment* (Deuteronomy 10:18), and those who are His imitate Him. It is the fast Yahuah (LORD) chooses: *to deal thy bread to the hungry, and that thou bring the poor that are cast out to thy house... and that thou hide not thyself from thine own flesh* (Isaiah 58:7). The restored library teaches the same hand to the needy — *Give of your bread to the hungry, and of your garments to them that are naked* (Tobit 4:16); *stretch yours hand to the poor, that your blessing may be perfected* (Sirach 7:32). And the King makes it a receiving of Himself: *I was a stranger, and ye took me in* (Matthew 25:35); so the apostolic word, *given to hospitality* (Romans 12:13). To receive the brethren *for his name''s sake* (3 John 7) is to keep the Torah''s love of the stranger and to become a fellowhelper to the truth.',
       sv.verse_id, ev.verse_id, 'extras', 10186
  FROM _s244_3john_lookup sv, _s244_3john_lookup ev
 WHERE sv.edition_slug='canon' AND sv.book_slug='3-john' AND sv.chapter_number=1 AND sv.verse_number=5
   AND ev.edition_slug='canon' AND ev.book_slug='3-john' AND ev.chapter_number=1 AND ev.verse_number=8
ON CONFLICT (slug) DO NOTHING;

-- ----- thread members -----
INSERT INTO cross_reference_thread_members (thread_id, cross_reference_id, sort_order, member_note)
SELECT t.id, cr.id, m.sort_order, m.member_note
  FROM (VALUES
    -- thread 1: Two-Ways test (v.11)
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','deuteronomy',30,15, 10, E'*See, I have set before thee this day life and good, and death and evil;* (Deuteronomy 30:15). The Two Ways at their root: Yahuah (LORD) sets before Yashar''el (Israel) life-and-good against death-and-evil. John''s *follow not that which is evil, but that which is good* (3 John 11) stands directly upon this choice.'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','psalms',34,14, 20, E'*Depart from evil, and do good; seek peace, and pursue it.* (Psalm 34:14). The ancient Two-Ways charge — turn from evil, do good — is the very test by which John says a man is shown to be of Yahuah (LORD).'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','psalms',37,27, 30, E'*Depart from evil, and do good; and dwell for evermore.* (Psalm 37:27). The psalm joins doing good to abiding for ever, as John joins it to belonging to Elohim (God): *He that doeth good is of Elohim (God)* (3 John 11).'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','isaiah',1,16, 40, E'*Wash you, make you clean; put away the evil of your doings from before mine eyes; cease to do evil;* (Isaiah 1:16). The first half of the test — *cease to do evil* — matching John''s *follow not that which is evil* (3 John 11).'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','isaiah',1,17, 50, E'*Learn to do well; seek judgment, relieve the oppressed, judge the fatherless, plead for the widow.* (Isaiah 1:17). The second half — *learn to do well* — filling out the good with the deeds of mercy and righteousness John''s *that which is good* (3 John 11) requires.'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','amos',5,14, 60, E'*Seek good, and not evil, that ye may live: and so Yahuah (LORD), the Elohim (God) of hosts, shall be with you, as ye have spoken.* (Amos 5:14). Amos ties seeking good to life and to Yahuah''s (LORD''s) presence, as John ties doing good to belonging.'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','amos',5,15, 70, E'*Hate the evil, and love the good, and establish judgment in the gate: it may be that Yahuah Elohim (the LORD God) of hosts will be gracious unto the remnant of Joseph.* (Amos 5:15). The test sharpened into the affections — *hate the evil, and love the good* — the mark of the remnant Yahuah (LORD) preserves.'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','proverbs',3,7, 80, E'*Be not wise in thine own eyes: fear Yahuah (LORD), and depart from evil.* (Proverbs 3:7). Wisdom binds the fear of Yahuah (LORD) to departing from evil — one motion with John''s *follow not that which is evil* (3 John 11).'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','1-john',3,7, 90, E'*Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous.* (1 John 3:7). John''s first letter, almost word for word: the doing is the proof — the same master-filter as *He that doeth good is of Elohim (God)* (3 John 11).'),
    ('3-john-1-follow-not-evil-but-good-he-that-doeth-good-is-of-elohim-the-two-ways-psalm-34-37-isaiah-1', 'canon','3-john',1,11, 'canon','1-john',3,10, 100, E'*In this the children of Elohim (God) are manifest, and the children of the devil: whosoever doeth not righteousness is not of Elohim (God), neither he that loveth not his brother.* (1 John 3:10). The deed makes manifest whose children men are — so *he that doeth evil hath not seen Elohim (God)* (3 John 11).'),
    -- thread 2: walking in truth (v.3-4)
    ('3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2', 'canon','3-john',1,3, 'canon','psalms',86,11, 10, E'*Teach me thy way, O Yahuah (LORD); I will walk in thy truth: unite my heart to fear thy name.* (Psalm 86:11). David prays the walk John rejoices to see in Gaius — *thou walkest in the truth* (3 John 3): the truth that is Yahuah''s (LORD''s) own way.'),
    ('3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2', 'canon','3-john',1,3, 'canon','psalms',119,1, 20, E'*Blessed are the undefiled in the way, who walk in the law of Yahuah (LORD).* (Psalm 119:1). To walk in the truth is to walk in His law, the undefiled way the psalm calls blessed.'),
    ('3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2', 'canon','3-john',1,3, 'canon','1-kings',2,4, 30, E'*...to walk before me in truth with all their heart and with all their soul, there shall not fail thee (said he) a man on the throne of Yashar''el (Israel).* (1 Kings 2:4). David''s charge makes walking in truth the covenant condition — the same fidelity John''s children keep (3 John 4).'),
    ('3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2', 'canon','3-john',1,3, 'canon','2-kings',20,3, 40, E'*...remember now how I have walked before thee in truth and with a perfect heart, and have done that which is good in thy sight.* (2 Kings 20:3). Hezekiah joins walking in truth to doing good — the two notes of this whole letter.'),
    ('3-john-1-walking-in-the-truth-psalm-86-119-1-kings-2', 'canon','3-john',1,3, 'canon','2-john',1,4, 50, E'*I rejoiced greatly that I found of thy children walking in truth, as we have received a commandment from the Father.* (2 John 4). The sister-letter''s identical joy and phrase — walking in truth as a commandment kept, not merely held.'),
    -- thread 3: receiving the brethren / love the stranger (v.5-8)
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','genesis',18,1, 10, E'*And Yahuah (LORD) appeared unto him in the plains of Mamre: and he sat in the tent door in the heat of the day;* (Genesis 18:1). The pattern of receiving the sent ones begins with Abraham at the tent door.'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','genesis',18,2, 20, E'*And he lift up his eyes and looked, and, lo, three men stood by him: and when he saw them, he ran to meet them from the tent door, and bowed himself toward the ground,* (Genesis 18:2). Abraham *ran to meet them* — the haste of true hospitality John commends in Gaius (3 John 5).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','genesis',18,8, 30, E'*And he took butter, and milk, and the calf which he had dressed, and set it before them; and he stood by them under the tree, and they did eat.* (Genesis 18:8). Abraham serves his guests — the faithful service to the travelling stranger John means by doing faithfully to the brethren and strangers (3 John 5).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','leviticus',19,34, 40, E'*But the stranger that dwelleth with you shall be unto you as one born among you, and thou shalt love him as thyself; for ye were strangers in the land of Egypt: I am Yahuah Elohaychem (the LORD your God).* (Leviticus 19:34). The Torah command beneath Gaius'' faithfulness to strangers (3 John 5).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','deuteronomy',10,18, 50, E'*He doth execute the judgment of the fatherless and widow, and loveth the stranger, in giving him food and raiment.* (Deuteronomy 10:18). Yahuah (LORD) Himself loves the stranger; those who are His imitate Him.'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','deuteronomy',10,19, 60, E'*Love ye therefore the stranger: for ye were strangers in the land of Egypt.* (Deuteronomy 10:19). The plain command, grounded in Yashar''el''s (Israel''s) own memory — kept in Gaius'' welcome of the brethren and strangers (3 John 5).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','isaiah',58,7, 70, E'*Is it not to deal thy bread to the hungry, and that thou bring the poor that are cast out to thy house?...* (Isaiah 58:7). The fast Yahuah (LORD) chooses — the open door John praises, that we might be fellowhelpers to the truth (3 John 8).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'apocrypha','tobit',4,16, 80, E'*Give of your bread to the hungry, and of your garments to them that are naked; and according to your abundance give alms...* (Tobit 4:16). The restored library''s household ethic of charity — the same hospitality John commends (3 John 5).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'apocrypha','ecclesiasticus',7,32, 90, E'*And stretch yours hand to the poor, that your blessing may be perfected.* (Sirach 7:32). The open hand to the needy by which a blessing is perfected — the fellowship that makes one a fellowhelper to the truth (3 John 8).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','matthew',25,35, 100, E'*For I was an hungred, and ye gave me meat: I was thirsty, and ye gave me drink: I was a stranger, and ye took me in:* (Matthew 25:35). The King makes receiving the stranger a receiving of Himself — exactly what John praises in Gaius (3 John 5).'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','hebrews',13,2, 110, E'*Be not forgetful to entertain strangers: for thereby some have entertained angels unawares.* (Hebrews 13:2). The exhortation looks straight back to Abraham at Mamre — the host of the sent ones may be hosting Yahuah''s (LORD''s) messengers.'),
    ('3-john-1-receiving-the-brethren-fellowhelpers-to-the-truth-love-the-stranger-leviticus-19-deuteronomy-10', 'canon','3-john',1,5, 'canon','romans',12,13, 120, E'*Distributing to the necessity of saints; given to hospitality.* (Romans 12:13). Paul names the same duty — *given to hospitality* — of which Gaius is the very pattern (3 John 5).')
  ) AS m(thread_slug, src_edition, src_slug, src_ch, src_v, tgt_edition, tgt_slug, tgt_ch, tgt_v, sort_order, member_note)
  JOIN cross_reference_threads t ON t.slug = m.thread_slug
  JOIN _s244_3john_lookup sv ON sv.edition_slug=m.src_edition AND sv.book_slug=m.src_slug AND sv.chapter_number=m.src_ch AND sv.verse_number=m.src_v
  JOIN _s244_3john_lookup tv ON tv.edition_slug=m.tgt_edition AND tv.book_slug=m.tgt_slug AND tv.chapter_number=m.tgt_ch AND tv.verse_number=m.tgt_v
  JOIN cross_references cr ON cr.source_verse_id=sv.verse_id AND cr.target_verse_id=tv.verse_id AND cr.source='manual'
ON CONFLICT (thread_id, cross_reference_id) DO NOTHING;
