-- =====================================================================
-- Session 204 seed v1 — THE WITNESS (Red Pill) starter set
-- =====================================================================
-- GENERATED by restoration-pipeline/_session204_build_red_pill_seed.py.
-- Do not hand-edit; edit the generator and re-run. Every quote is the
-- exact restored verse text from canon.json. 30 cards /
-- 39 marked verses (Tanakh anchors carry the mark too —
-- full-canon V1 per Yoshi's S204 call).
-- Idempotent: ON CONFLICT (verse_id) DO UPDATE refreshes cards.
-- Run: python3 api/apply_migration.py data-schema/migrations/session204_red_pill_seed_v1.sql
-- =====================================================================

BEGIN;

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 8 AND v.verse_number = 58), 'direct', 'His own mouth', 'Before Abraham was — I AM', $card$*Yahusha (Jesus) said unto them, Verily, verily, I say unto you, Before Abraham was, I am.* (John 8:58)

*And Elohim (God) said unto Moses, Ehyeh asher Ehyeh (I AM THAT I AM): and he said, Thus shalt thou say unto the children of Yashar'el (Israel), I AM hath sent me unto you.* (Exodus 3:14)

The name spoken at the bush is the name he takes up in the temple court. He does not say *before Abraham was, I existed* — the language had plain ways to say that. He says *I AM*, the name Elohim (God) gave Moses to carry to the children of Yashar'el (Israel). And the crowd hears exactly what he claimed:

*Then took they up stones to cast at him: but Yahusha (Jesus) hid himself, and went out of the temple, going through the midst of them, and so passed by.* (John 8:59)

Stoning was the penalty for blasphemy. There is no third reading: either he is claiming the I AM of the bush as his own name, or the claim is blasphemy and the stones were right. The inherited view has always heard deity in this verse — rightly. What it misses is who stood at the bush:

*No man hath seen Elohim (God) at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him.* (John 1:18)

The Father is the Formless, whom no eye has seen. The one who appeared at the bush, who spoke, who sent Moses, who led Yashar'el (Israel) out — that was the Formed, the Word who would come in the flesh. He is not borrowing the name. He is answering to it.$card$, '{"Exodus 3:14","John 8:59"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'exodus' AND c.chapter_number = 3 AND v.verse_number = 14), 'direct', 'His own mouth', 'Before Abraham was — I AM', $card$*Yahusha (Jesus) said unto them, Verily, verily, I say unto you, Before Abraham was, I am.* (John 8:58)

*And Elohim (God) said unto Moses, Ehyeh asher Ehyeh (I AM THAT I AM): and he said, Thus shalt thou say unto the children of Yashar'el (Israel), I AM hath sent me unto you.* (Exodus 3:14)

The name spoken at the bush is the name he takes up in the temple court. He does not say *before Abraham was, I existed* — the language had plain ways to say that. He says *I AM*, the name Elohim (God) gave Moses to carry to the children of Yashar'el (Israel). And the crowd hears exactly what he claimed:

*Then took they up stones to cast at him: but Yahusha (Jesus) hid himself, and went out of the temple, going through the midst of them, and so passed by.* (John 8:59)

Stoning was the penalty for blasphemy. There is no third reading: either he is claiming the I AM of the bush as his own name, or the claim is blasphemy and the stones were right. The inherited view has always heard deity in this verse — rightly. What it misses is who stood at the bush:

*No man hath seen Elohim (God) at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him.* (John 1:18)

The Father is the Formless, whom no eye has seen. The one who appeared at the bush, who spoke, who sent Moses, who led Yashar'el (Israel) out — that was the Formed, the Word who would come in the flesh. He is not borrowing the name. He is answering to it.$card$, '{"Exodus 3:14","John 8:59"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 10 AND v.verse_number = 30), 'direct', 'His own mouth', 'I and my Father are one', $card$*I and my Father are one.* (John 10:30)

*Hear, O Yashar'el (Israel): Yahuah Eloheinu (The LORD our God) is one Yahuah (LORD):* (Deuteronomy 6:4)

The hearers in the temple did not take this as a figure of speech about agreement. They reached for stones, and they said why:

*The Yahudim (Jews) answered him, saying, For a good work we stone thee not; but for blasphemy; and because that thou, being a man, makest thyself Elohim (God).* (John 10:33)

The charge is exact: *thou, being a man, makest thyself Elohim (God).* They heard a man stand inside the Shema — the oneness that belongs to Yahuah (God) alone — and claim it. The Father is the Formless; the Son is the Formed, drawn from him, eternally submitted to him, one with him. He has a Father, and he is one with the Father — the canon holds both without strain, and this verse is where it says so.$card$, '{"Deuteronomy 6:4","John 10:33"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 20 AND v.verse_number = 28), 'direct', 'Spoken of him', 'My Lord and my Elohim (God)', $card$*And Thomas answered and said unto him, My Lord and my Elohim (God).* (John 20:28)

*I am Yahuah (LORD): that is my name: and my glory will I not give to another, neither my praise to graven images.* (Isaiah 42:8)

Thomas, a Torah-keeping son of Yashar'el (Israel), addresses the risen one to his face: *my Lord and my Elohim (God).* If the address were too high, this is the moment to refuse it — Yahuah (God) does not give his glory to another. Instead:

*Yahusha (Jesus) saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed.* (John 20:29)

He receives the address and blesses everyone who will make it without seeing. The one who will not share his glory accepts this glory — because it is his.$card$, '{"Isaiah 42:8","John 20:29"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'mark' AND c.chapter_number = 2 AND v.verse_number = 10), 'direct', 'His own mouth', 'Who can forgive sins but Elohim (God) only?', $card$*When Yahusha (Jesus) saw their faith, he said unto the sick of the palsy, Son, thy sins be forgiven thee. But there were certain of the scribes sitting there, and reasoning in their hearts, Why doth this man thus speak blasphemies? who can forgive sins but Elohim (God) only?* (Mark 2:5-7)

*I, even I, am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.* (Isaiah 43:25)

The scribes' theology is correct: sin is against Yahuah (God), so only Yahuah (God) can blot it out — *I, even I, am he.* Their question is the right question. His answer is not a correction of their theology but a demonstration in front of their eyes:

*But that ye may know that the Son of Adam hath power on earth to forgive sins, (he saith to the sick of the palsy,) I say unto thee, Arise, and take up thy bed, and go thy way into thine house.* (Mark 2:10-11)

The Son of Adam does on earth what the Tanakh says Yahuah (God) alone does. The paralytic walks so that the scribes — and the reader — may know whose authority just spoke.$card$, '{"Isaiah 43:25","Mark 2:5-7"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'mark' AND c.chapter_number = 14 AND v.verse_number = 62), 'direct', 'His own mouth', 'Ye shall see the Son of Adam coming in the clouds', $card$*But he held his peace, and answered nothing. Again the high priest asked him, and said unto him, Art thou the Messiah (Christ), the Son of the Blessed? And Yahusha (Jesus) said, I am: and ye shall see the Son of Adam sitting on the right hand of power, and coming in the clouds of heaven.* (Mark 14:61-62)

*I saw in the night visions, and, behold, one like the Son of Adam came with the clouds of heaven, and came to the Ancient of days, and they brought him near before him. And there was given him dominion, and glory, and a kingdom, that all people, nations, and languages, should serve him: his dominion is an everlasting dominion, which shall not pass away, and his kingdom that which shall not be destroyed.* (Daniel 7:13-14)

Asked under oath whether he is the Messiah (Christ), he answers *I am* — and then places himself inside Daniel's night vision. Notice what Daniel's text actually says: *one LIKE the Son of Adam.* The comparison is the text's own move, and it is worth keeping. The figure rides the clouds — and everywhere else in scripture the cloud-rider is Yahuah (God) himself — yet he is *like* a son of Adam. The vision holds both: one who bears the form of Adam's line and arrives on the clouds no creature rides, receiving an everlasting kingdom that shall not be destroyed. He resembled mortal man because he took on flesh; he remained the cloud-rider. At the trial he claims that seat in the first person, and the high priest tears his clothes — he heard the claim exactly.$card$, '{"Daniel 7:13-14","Mark 14:61"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'daniel' AND c.chapter_number = 7 AND v.verse_number = 13), 'direct', 'His own mouth', 'Ye shall see the Son of Adam coming in the clouds', $card$*But he held his peace, and answered nothing. Again the high priest asked him, and said unto him, Art thou the Messiah (Christ), the Son of the Blessed? And Yahusha (Jesus) said, I am: and ye shall see the Son of Adam sitting on the right hand of power, and coming in the clouds of heaven.* (Mark 14:61-62)

*I saw in the night visions, and, behold, one like the Son of Adam came with the clouds of heaven, and came to the Ancient of days, and they brought him near before him. And there was given him dominion, and glory, and a kingdom, that all people, nations, and languages, should serve him: his dominion is an everlasting dominion, which shall not pass away, and his kingdom that which shall not be destroyed.* (Daniel 7:13-14)

Asked under oath whether he is the Messiah (Christ), he answers *I am* — and then places himself inside Daniel's night vision. Notice what Daniel's text actually says: *one LIKE the Son of Adam.* The comparison is the text's own move, and it is worth keeping. The figure rides the clouds — and everywhere else in scripture the cloud-rider is Yahuah (God) himself — yet he is *like* a son of Adam. The vision holds both: one who bears the form of Adam's line and arrives on the clouds no creature rides, receiving an everlasting kingdom that shall not be destroyed. He resembled mortal man because he took on flesh; he remained the cloud-rider. At the trial he claims that seat in the first person, and the high priest tears his clothes — he heard the claim exactly.$card$, '{"Daniel 7:13-14","Mark 14:61"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'revelation' AND c.chapter_number = 1 AND v.verse_number = 8), 'direct', 'His own mouth', 'Alpha and Omega — which is, and which was, and which is to come', $card$*Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him: and all kindreds of the earth shall wail because of him. Even so, Amen. I am Alpha and Omega, the beginning and the ending, saith Yahuah (Lord), which is, and which was, and which is to come, the Almighty.* (Revelation 1:7-8)

*Who hath wrought and done it, calling the generations from the beginning? I Yahuah (LORD), the first, and with the last; I am he.* (Isaiah 41:4)

The speaker of verse 8 is the one verse 7 says is coming with clouds — the pierced one. He names himself with Yahuah (God)'s own self-description from the prophets: the first, with the last, *I am he.* The Almighty's name in the mouth of the one who was pierced.$card$, '{"Isaiah 41:4","Revelation 1:7"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'revelation' AND c.chapter_number = 1 AND v.verse_number = 17), 'direct', 'His own mouth', 'The first and the last — who was dead, and is alive', $card$*And when I saw him, I fell at his feet as dead. And he laid his right hand upon me, saying unto me, Fear not; I am the first and the last: I am he that liveth, and was dead; and, behold, I am alive for evermore, Amen; and have the keys of hell and of death.* (Revelation 1:17-18)

*Thus saith Yahuah (LORD) the King of Yashar'el (Israel), and his redeemer Yahuah Tseva'ot (LORD of hosts); I am the first, and I am the last; and beside me there is no Elohim (God).* (Isaiah 44:6)

In Isaiah, *I am the first, and I am the last* is spoken by Yahuah (LORD) the King of Yashar'el (Israel), with the verdict attached: *beside me there is no Elohim (God).* In Revelation the same title is spoken by one who *was dead and is alive for evermore.* Yahuah (God) does not share that title — and the Father, the Formless, did not die. Either the verse breaks Isaiah, or the Formed — the one who came in the flesh, died, and rose — is the first and the last of Isaiah's own mouth.$card$, '{"Isaiah 44:6"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = '1-corinthians' AND c.chapter_number = 12 AND v.verse_number = 3), 'direct', 'Spoken of him', 'No man can say it but by the Ruach HaKodesh (Holy Spirit)', $card$*Wherefore I give you to understand, that no man speaking by the Spirit of Elohim (God) calleth Yahusha (Jesus) accursed: and that no man can say that Yahusha (Jesus) is Yahuah (Lord), but by the Ruach HaKodesh (Holy Spirit).* (1 Corinthians 12:3)

*And it shall come to pass, that whosoever shall call on the name of Yahuah (LORD) shall be delivered: for in mount Zion and in Jerusalem shall be deliverance, as Yahuah (LORD) hath said, and in the remnant whom Yahuah (LORD) shall call.* (Joel 2:32)

*For whosoever shall call upon the name of Yahuah (Lord) shall be saved.* (Romans 10:13)

Paul quotes Joel's promise — call on the name of Yahuah (LORD) and be delivered — and lands it on Yahusha (Jesus). And he tells the Corinthians plainly that the confession *Yahusha (Jesus) is Yahuah (Lord)* is not a conclusion flesh reaches on its own: only the Ruach HaKodesh (Holy Spirit) reveals it. The equation is the Spirit's own teaching — the center the rest of these marked verses keep returning to.$card$, '{"Joel 2:32","Romans 10:13"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'philippians' AND c.chapter_number = 2 AND v.verse_number = 10), 'direct', 'Spoken of him', 'Every knee shall bow, every tongue shall swear', $card$*Wherefore Elohim (God) also hath highly exalted him, and given him a name which is above every name: That at the name of Yahusha (Jesus) every knee should bow, of things in heaven, and things in earth, and things under the earth; And that every tongue should confess that Yahusha HaMashiach (Jesus Christ) is Lord, to the glory of Elohim (God) the Father.* (Philippians 2:9-11)

*Look unto me, and be ye saved, all the ends of the earth: for I am Elohim (God), and there is none else. I have sworn by myself, the word is gone out of my mouth in righteousness, and shall not return, That unto me every knee shall bow, every tongue shall swear.* (Isaiah 45:22-23)

Isaiah's oath could not be more guarded: *I am Elohim (God), and there is none else... unto ME every knee shall bow.* Yahuah (God) swore it by himself. Paul takes that sworn, unshareable homage and writes it onto the name of Yahusha (Jesus) — to the glory of Elohim (God) the Father. The Formed receives the bow the Formless swore to himself, and the Father is glorified in it. That is either the deepest harmony in the canon, or a contradiction at its center. The verses, side by side, let you watch which.$card$, '{"Isaiah 45:22-23"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 9 AND v.verse_number = 38), 'direct', 'Worship received', 'And he worshipped him', $card$*And Yahusha (Jesus) said unto him, Thou hast both seen him, and it is he that talketh with thee. And he said, Lord, I believe. And he worshipped him.* (John 9:37-38)

*For thou shalt worship no other god: for Yahuah (LORD), whose name is Jealous, is a jealous Elohim (God):* (Exodus 34:14)

The healed man worships, and Yahusha (Jesus) receives it without a word of correction. Compare what a faithful messenger does when worship lands on him by mistake:

*And I fell at his feet to worship him. And he said unto me, See thou do it not: I am thy fellowservant, and of thy brethren that have the testimony of Yahusha (Jesus): worship Elohim (God): for the testimony of Yahusha (Jesus) is the spirit of prophecy.* (Revelation 19:10)

The angel refuses instantly — *worship Elohim (God).* Every faithful creature in scripture deflects worship on contact. He never does. Worship belongs to Yahuah (God) alone, and he receives it as his own.$card$, '{"Exodus 34:14","Revelation 19:10"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'mark' AND c.chapter_number = 2 AND v.verse_number = 28), 'direct', 'His own mouth', 'Lord also of the sabbath', $card$*And he said unto them, The sabbath was made for man, and not man for the sabbath: Therefore the Son of Adam is Yahuah (Lord) also of the sabbath.* (Mark 2:27-28)

*But the seventh day is the sabbath of Yahuah Elohayka (the LORD thy God): in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant, nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates:* (Exodus 20:10)

*If thou turn away thy foot from the sabbath, from doing thy pleasure on my holy day; and call the sabbath a delight, the holy of Yahuah (LORD), honourable; and shalt honour him, not doing thine own ways, nor finding thine own pleasure, nor speaking thine own words:* (Isaiah 58:13)

The sabbath is not a free-floating institution anyone might administer. It is *the sabbath of Yahuah Elohayka (the LORD thy God)* — Yahuah (God) calls it *my holy day.* To stand in Galilee and claim lordship over that day is to claim the day's owner's seat. The Son of Adam claims it.$card$, '{"Exodus 20:10","Isaiah 58:13"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 10 AND v.verse_number = 11), 'title', 'The title transferred', 'I am the good shepherd', $card$*I am the good shepherd: the good shepherd giveth his life for the sheep.* (John 10:11)

*For thus saith Adonai Yahuah (the Lord GOD); Behold, I, even I, will both search my sheep, and seek them out. As a shepherd seeketh out his flock in the day that he is among his sheep that are scattered; so will I seek out my sheep, and will deliver them out of all places where they have been scattered in the cloudy and dark day.* (Ezekiel 34:11-12)

*I will feed my flock, and I will cause them to lie down, saith Adonai Yahuah (the Lord GOD).* (Ezekiel 34:15)

*Yahuah Ra'ah (The LORD is my shepherd); I shall not want.* (Psalm 23:1)

In Ezekiel, Adonai Yahuah (the Lord GOD) takes the shepherd's office into his own hands — *I, even I, will both search my sheep... I will feed my flock.* David's psalm names the shepherd outright: Yahuah Ra'ah (The LORD is my shepherd). Then the Formed stands in Yerushalayim (Jerusalem) and says *I am the good shepherd* — the office Yahuah (God) reserved for himself, claimed in the first person. And notice which sheep Ezekiel's shepherd comes for: the flock *scattered in the cloudy and dark day.* The shepherd's claim and the gathering of scattered Yashar'el (Israel) are one fabric — he is who he says, doing what Yahuah (God) said he himself would do.$card$, '{"Ezekiel 34:11-15","Psalm 23:1"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'ezekiel' AND c.chapter_number = 34 AND v.verse_number = 11), 'title', 'The title transferred', 'I am the good shepherd', $card$*I am the good shepherd: the good shepherd giveth his life for the sheep.* (John 10:11)

*For thus saith Adonai Yahuah (the Lord GOD); Behold, I, even I, will both search my sheep, and seek them out. As a shepherd seeketh out his flock in the day that he is among his sheep that are scattered; so will I seek out my sheep, and will deliver them out of all places where they have been scattered in the cloudy and dark day.* (Ezekiel 34:11-12)

*I will feed my flock, and I will cause them to lie down, saith Adonai Yahuah (the Lord GOD).* (Ezekiel 34:15)

*Yahuah Ra'ah (The LORD is my shepherd); I shall not want.* (Psalm 23:1)

In Ezekiel, Adonai Yahuah (the Lord GOD) takes the shepherd's office into his own hands — *I, even I, will both search my sheep... I will feed my flock.* David's psalm names the shepherd outright: Yahuah Ra'ah (The LORD is my shepherd). Then the Formed stands in Yerushalayim (Jerusalem) and says *I am the good shepherd* — the office Yahuah (God) reserved for himself, claimed in the first person. And notice which sheep Ezekiel's shepherd comes for: the flock *scattered in the cloudy and dark day.* The shepherd's claim and the gathering of scattered Yashar'el (Israel) are one fabric — he is who he says, doing what Yahuah (God) said he himself would do.$card$, '{"Ezekiel 34:11-15","Psalm 23:1"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'psalms' AND c.chapter_number = 23 AND v.verse_number = 1), 'title', 'The title transferred', 'I am the good shepherd', $card$*I am the good shepherd: the good shepherd giveth his life for the sheep.* (John 10:11)

*For thus saith Adonai Yahuah (the Lord GOD); Behold, I, even I, will both search my sheep, and seek them out. As a shepherd seeketh out his flock in the day that he is among his sheep that are scattered; so will I seek out my sheep, and will deliver them out of all places where they have been scattered in the cloudy and dark day.* (Ezekiel 34:11-12)

*I will feed my flock, and I will cause them to lie down, saith Adonai Yahuah (the Lord GOD).* (Ezekiel 34:15)

*Yahuah Ra'ah (The LORD is my shepherd); I shall not want.* (Psalm 23:1)

In Ezekiel, Adonai Yahuah (the Lord GOD) takes the shepherd's office into his own hands — *I, even I, will both search my sheep... I will feed my flock.* David's psalm names the shepherd outright: Yahuah Ra'ah (The LORD is my shepherd). Then the Formed stands in Yerushalayim (Jerusalem) and says *I am the good shepherd* — the office Yahuah (God) reserved for himself, claimed in the first person. And notice which sheep Ezekiel's shepherd comes for: the flock *scattered in the cloudy and dark day.* The shepherd's claim and the gathering of scattered Yashar'el (Israel) are one fabric — he is who he says, doing what Yahuah (God) said he himself would do.$card$, '{"Ezekiel 34:11-15","Psalm 23:1"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'mark' AND c.chapter_number = 2 AND v.verse_number = 19), 'title', 'The title transferred', 'The bridegroom', $card$*And Yahusha (Jesus) said unto them, Can the children of the bridechamber fast, while the bridegroom is with them? as long as they have the bridegroom with them, they cannot fast. But the days will come, when the bridegroom shall be taken away from them, and then shall they fast in those days.* (Mark 2:19-20)

*For thy Maker is thine husband; Yahuah Tseva'ot (LORD of hosts) is his name; and thy Redeemer the Holy One of Yashar'el (Israel); The Elohim (God) of the whole earth shall he be called.* (Isaiah 54:5)

*And I will betroth thee unto me for ever; yea, I will betroth thee unto me in righteousness, and in judgment, and in lovingkindness, and in mercies. I will even betroth thee unto me in faithfulness: and thou shalt know Yahuah (LORD).* (Hosea 2:19-20)

Asked about fasting, he answers with a title: the bridegroom is here. In the prophets there is exactly one husband of the covenant people — *thy Maker is thine husband; Yahuah Tseva'ot (LORD of hosts) is his name* — and exactly one betrothal promised: *I will betroth thee unto me for ever.* A rabbi calling himself the bridegroom of Yashar'el (Israel) is not reaching for a wedding metaphor. He is standing in the husband's place.$card$, '{"Isaiah 54:5","Hosea 2:19-20"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 8 AND v.verse_number = 12), 'title', 'The title transferred', 'I am the light of the world', $card$*Then spake Yahusha (Jesus) again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.* (John 8:12)

*Yahuah (LORD) is my light and my salvation; whom shall I fear? Yahuah (LORD) is the strength of my life; of whom shall I be afraid?* (Psalm 27:1)

*The sun shall be no more thy light by day; neither for brightness shall the moon give light unto thee: but Yahuah (LORD) shall be unto thee an everlasting light, and thy Elohim (God) thy glory.* (Isaiah 60:19)

*Yahuah (LORD) is my light* — David's confession, and Isaiah's promise of the age to come: Yahuah (LORD) himself an everlasting light in place of the sun. The one speaking in the treasury of the temple claims the title as his own present tense — *I am the light of the world* — and attaches to it what only the source of light can give: *the light of life.*$card$, '{"Psalm 27:1","Isaiah 60:19"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 12 AND v.verse_number = 13), 'title', 'The title transferred', 'The King of Yashar''el (Israel)', $card$*Took branches of palm trees, and went forth to meet him, and cried, Hosanna: Blessed is the King of Yashar'el (Israel) that cometh in the name of Yahuah (Lord).* (John 12:13)

*Yahuah (LORD) hath taken away thy judgments, he hath cast out thine enemy: the king of Yashar'el (Israel), even Yahuah (LORD), is in the midst of thee: thou shalt not see evil any more.* (Zephaniah 3:15)

*Thus saith Yahuah (LORD) the King of Yashar'el (Israel), and his redeemer Yahuah Tseva'ot (LORD of hosts); I am the first, and I am the last; and beside me there is no Elohim (God).* (Isaiah 44:6)

The crowds at the gate hail him as the King of Yashar'el (Israel). In the prophets that throne is occupied: *the king of Yashar'el (Israel), even Yahuah (LORD), is in the midst of thee.* Isaiah binds the title tighter still — Yahuah (LORD) the King of Yashar'el (Israel), beside whom there is no Elohim (God). Zephaniah's words land with strange precision: the King of Yashar'el (Israel), Yahuah (LORD), *in the midst of thee* — and there he is, riding through the midst of Yerushalayim (Jerusalem).$card$, '{"Zephaniah 3:15","Isaiah 44:6"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'revelation' AND c.chapter_number = 22 AND v.verse_number = 12), 'title', 'The title transferred', 'My reward is with me', $card$*And, behold, I come quickly; and my reward is with me, to give every man according as his work shall be. I am Alpha and Omega, the beginning and the end, the first and the last.* (Revelation 22:12-13)

*Behold, Adonai Yahuah (the Lord GOD) will come with strong hand, and his arm shall rule for him: behold, his reward is with him, and his work before him.* (Isaiah 40:10)

Isaiah announces Adonai Yahuah (the Lord GOD) coming with strong hand — *behold, his reward is with him, and his work before him.* The voice at the end of the canon takes the sentence into the first person: *behold, I come quickly; and my reward is with me* — and seals it with the unshareable name: Alpha and Omega, the first and the last. Isaiah's coming Yahuah (God) speaks in Revelation as I.$card$, '{"Isaiah 40:10","Revelation 22:13"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'luke' AND c.chapter_number = 21 AND v.verse_number = 27), 'act', 'The act transferred', 'His feet on the mount of Olives', $card$*And then shall they see the Son of Adam coming in a cloud with power and great glory.* (Luke 21:27)

*Then shall Yahuah (LORD) go forth, and fight against those nations, as when he fought in the day of battle. And his feet shall stand in that day upon the mount of Olives, which is before Jerusalem on the east, and the mount of Olives shall cleave in the midst thereof toward the east and toward the west, and there shall be a very great valley; and half of the mountain shall remove toward the north, and half of it toward the south.* (Zechariah 14:3-4)

*Which also said, Ye men of Galilee, why stand ye gazing up into heaven? this same Yahusha (Jesus), which is taken up from you into heaven, shall so come in like manner as ye have seen him go into heaven. Then returned they unto Jerusalem from the mount called Olivet, which is from Jerusalem a sabbath day’s journey.* (Acts 1:11-12)

Zechariah gives the day of battle to Yahuah (LORD) in person — he goes forth, he fights, *his feet shall stand in that day upon the mount of Olives.* Then watch the geography of the ascension: Yahusha (Jesus) is taken up FROM Olivet, and the messengers promise he will return *in like manner* — to the same mountain Zechariah reserved for the feet of Yahuah (LORD). The Son of Adam coming in a cloud, and Yahuah (LORD) going forth to fight, arrive at the same spot of ground on the same day.$card$, '{"Zechariah 14:3-4","Acts 1:11-12"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'zechariah' AND c.chapter_number = 14 AND v.verse_number = 4), 'act', 'The act transferred', 'His feet on the mount of Olives', $card$*And then shall they see the Son of Adam coming in a cloud with power and great glory.* (Luke 21:27)

*Then shall Yahuah (LORD) go forth, and fight against those nations, as when he fought in the day of battle. And his feet shall stand in that day upon the mount of Olives, which is before Jerusalem on the east, and the mount of Olives shall cleave in the midst thereof toward the east and toward the west, and there shall be a very great valley; and half of the mountain shall remove toward the north, and half of it toward the south.* (Zechariah 14:3-4)

*Which also said, Ye men of Galilee, why stand ye gazing up into heaven? this same Yahusha (Jesus), which is taken up from you into heaven, shall so come in like manner as ye have seen him go into heaven. Then returned they unto Jerusalem from the mount called Olivet, which is from Jerusalem a sabbath day’s journey.* (Acts 1:11-12)

Zechariah gives the day of battle to Yahuah (LORD) in person — he goes forth, he fights, *his feet shall stand in that day upon the mount of Olives.* Then watch the geography of the ascension: Yahusha (Jesus) is taken up FROM Olivet, and the messengers promise he will return *in like manner* — to the same mountain Zechariah reserved for the feet of Yahuah (LORD). The Son of Adam coming in a cloud, and Yahuah (LORD) going forth to fight, arrive at the same spot of ground on the same day.$card$, '{"Zechariah 14:3-4","Acts 1:11-12"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'mark' AND c.chapter_number = 6 AND v.verse_number = 48), 'act', 'The act transferred', 'Walking upon the sea', $card$*And he saw them toiling in rowing; for the wind was contrary unto them: and about the fourth watch of the night he cometh unto them, walking upon the sea, and would have passed by them. But when they saw him walking upon the sea, they supposed it had been a spirit, and cried out: For they all saw him, and were troubled. And immediately he talked with them, and saith unto them, Be of good cheer: it is I; be not afraid.* (Mark 6:48-50)

*Which alone spreadeth out the heavens, and treadeth upon the waves of the sea.* (Job 9:8)

Job's confession is categorical: the one *which ALONE spreadeth out the heavens, and treadeth upon the waves of the sea.* Alone. No agent, no deputy — the sea's waves are Yahuah (God)'s own footpath and no one else's. Then the disciples watch a figure tread the waves of Galilee, and his word to them is *It is I* — literally, *I AM; be not afraid.* The act that belongs to one alone, performed by one who answers with the name.$card$, '{"Job 9:8"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'luke' AND c.chapter_number = 22 AND v.verse_number = 20), 'act', 'The act transferred', 'The new covenant — cut in his own blood', $card$*Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you.* (Luke 22:20)

*Behold, the days come, saith Yahuah (LORD), that I will make a new covenant with the house of Yashar'el (Israel), and with the house of Yahudah (Judah):* (Jeremiah 31:31)

*But this shall be the covenant that I will make with the house of Yashar'el (Israel); After those days, saith Yahuah (LORD), I will put my law in their inward parts, and write it in their hearts; and will be their Elohim (God), and they shall be my people.* (Jeremiah 31:33)

Jeremiah's promise is unambiguous about whose covenant the new covenant is: *I will make... saith Yahuah (LORD)* — with the house of Yashar'el (Israel) and the house of Yahudah (Judah), Torah written on the heart. Covenants are cut in blood, and the covenant-maker provides it. At the table, the Formed lifts the cup and cuts Yahuah (LORD)'s promised covenant *in my blood.* Only the covenant's owner can cut it — and he cuts it in himself.$card$, '{"Jeremiah 31:31-33"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'jeremiah' AND c.chapter_number = 31 AND v.verse_number = 31), 'act', 'The act transferred', 'The new covenant — cut in his own blood', $card$*Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you.* (Luke 22:20)

*Behold, the days come, saith Yahuah (LORD), that I will make a new covenant with the house of Yashar'el (Israel), and with the house of Yahudah (Judah):* (Jeremiah 31:31)

*But this shall be the covenant that I will make with the house of Yashar'el (Israel); After those days, saith Yahuah (LORD), I will put my law in their inward parts, and write it in their hearts; and will be their Elohim (God), and they shall be my people.* (Jeremiah 31:33)

Jeremiah's promise is unambiguous about whose covenant the new covenant is: *I will make... saith Yahuah (LORD)* — with the house of Yashar'el (Israel) and the house of Yahudah (Judah), Torah written on the heart. Covenants are cut in blood, and the covenant-maker provides it. At the table, the Formed lifts the cup and cuts Yahuah (LORD)'s promised covenant *in my blood.* Only the covenant's owner can cut it — and he cuts it in himself.$card$, '{"Jeremiah 31:31-33"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 10 AND v.verse_number = 16), 'act', 'The act transferred', 'Other sheep — one fold, one shepherd', $card$*And other sheep I have, which are not of this fold: them also I must bring, and they shall hear my voice; and there shall be one fold, and one shepherd.* (John 10:16)

*As a shepherd seeketh out his flock in the day that he is among his sheep that are scattered; so will I seek out my sheep, and will deliver them out of all places where they have been scattered in the cloudy and dark day.* (Ezekiel 34:12)

*And say unto them, Thus saith Adonai Yahuah (the Lord GOD); Behold, I will take the children of Yashar'el (Israel) from among the heathen, whither they be gone, and will gather them on every side, and bring them into their own land:* (Ezekiel 37:21)

*I will seek out my sheep... I will take the children of Yashar'el (Israel) from among the heathen... and gather them.* The gathering of the scattered flock is Yahuah (God)'s own promised act, in his own first person. The shepherd speaking in John claims sheep *not of this fold* — the scattered house, sown among the nations — and takes the gathering on himself: *them also I MUST bring.* One flock, one shepherd: Ezekiel's words, his mouth. The claim of deity and the gathering of Yashar'el (Israel) are one announcement.$card$, '{"Ezekiel 34:12","Ezekiel 37:21"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'matthew' AND c.chapter_number = 15 AND v.verse_number = 24), 'act', 'The act transferred', 'Sent to the lost sheep of the house of Yashar''el (Israel)', $card$*But he answered and said, I am not sent but unto the lost sheep of the house of Yashar'el (Israel).* (Matthew 15:24)

*My people hath been lost sheep: their shepherds have caused them to go astray, they have turned them away on the mountains: they have gone from mountain to hill, they have forgotten their restingplace.* (Jeremiah 50:6)

*For thus saith Adonai Yahuah (the Lord GOD); Behold, I, even I, will both search my sheep, and seek them out. As a shepherd seeketh out his flock in the day that he is among his sheep that are scattered; so will I seek out my sheep, and will deliver them out of all places where they have been scattered in the cloudy and dark day.* (Ezekiel 34:11-12)

*My people hath been lost sheep* — Jeremiah names them, and Ezekiel records whose job their recovery is: *I, even I, will both search my sheep, and seek them out.* When Yahusha (Jesus) defines his entire mission as the lost sheep of the house of Yashar'el (Israel), he is not narrowing his compassion — he is executing the search Yahuah (God) said he himself would make. The seeker Ezekiel promised has arrived, on foot.$card$, '{"Jeremiah 50:6","Ezekiel 34:11-12"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'matthew' AND c.chapter_number = 25 AND v.verse_number = 31), 'act', 'The act transferred', 'The shepherd who judges between sheep and goats', $card$*When the Son of Adam shall come in his glory, and all the holy angels with him, then shall he sit upon the throne of his glory: And before him shall be gathered all nations: and he shall separate them one from another, as a shepherd divideth his sheep from the goats:* (Matthew 25:31-32)

*And as for you, O my flock, thus saith Adonai Yahuah (the Lord GOD); Behold, I judge between cattle and cattle, between the rams and the he goats.* (Ezekiel 34:17)

In Ezekiel the shepherd-judgment is Yahuah (God)'s own verdict in his own flock — *I judge between cattle and cattle, between the rams and the he goats,* spoken by Adonai Yahuah (the Lord GOD) over the gathered sheep. In Matthew, the Son of Adam sits on the throne of his glory, the flock gathered out of all nations before him, and the dividing staff is in his hand. The seat Ezekiel's *I* occupies is the seat he takes — the shepherd doing the shepherd-owner's own separating.$card$, '{"Ezekiel 34:17"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'romans' AND c.chapter_number = 7 AND v.verse_number = 4), 'structural', 'Only possible if', 'The first husband died', $card$*For the woman which hath an husband is bound by the law to her husband so long as he liveth; but if the husband be dead, she is loosed from the law of her husband. So then if, while her husband liveth, she be married to another man, she shall be called an adulteress: but if her husband be dead, she is free from that law; so that she is no adulteress, though she be married to another man.* (Romans 7:2-3)

*And I saw, when for all the causes whereby backsliding Yashar'el (Israel) committed adultery I had put her away, and given her a bill of divorce; yet her treacherous sister Yahudah (Judah) feared not, but went and played the harlot also.* (Jeremiah 3:8)

*Her former husband, which sent her away, may not take her again to be his wife, after that she is defiled; for that is abomination before Yahuah (LORD): and thou shalt not cause the land to sin, which Yahuah Elohayka (the LORD thy God) giveth thee for an inheritance.* (Deuteronomy 24:4)

Hold the three together and the dilemma closes like a vise. The northern house of Yashar'el (Israel) was not merely scattered — she was DIVORCED, bill of divorce in hand. And the Torah bars the road home: her former husband *may not take her again.* Yet the prophets promise remarriage:

*And I will betroth thee unto me for ever; yea, I will betroth thee unto me in righteousness, and in judgment, and in lovingkindness, and in mercies. I will even betroth thee unto me in faithfulness: and thou shalt know Yahuah (LORD).* (Hosea 2:19-20)

How can the promise keep the Torah? Paul's answer hangs on the one fact the wife's bond turns on — *if the husband be dead, she is loosed from the law of her husband:*

*Wherefore, my brethren, ye also are become dead to the law by the body of Messiah (Christ); that ye should be married to another, even to him who is raised from the dead, that we should bring forth fruit unto Elohim (God).* (Romans 7:4)

*Dead to the law by the body of Messiah (Christ)* — not the Torah dissolved, but the marriage-bond satisfied, because the husband himself died. The argument only functions if the one who died on the tree IS the husband who covenanted at Sinai — the Formed, who took flesh, died, and rose. The divorced house is freed by his death and married to him raised: Hosea's betrothal, legally clean, the Torah unbroken. One argument — and the whole good news of the gathering inside it.$card$, '{"Jeremiah 3:8","Deuteronomy 24:4","Hosea 2:19-20"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 14 AND v.verse_number = 15), 'structural', 'Only possible if', 'MY commandments — the ME of Sinai', $card$*If ye love me, keep my commandments.* (John 14:15)

*And shewing mercy unto thousands of them that love me, and keep my commandments.* (Exodus 20:6)

The second commandment describes its own people: *them that love ME, and keep MY commandments* — the me is Yahuah (God) speaking from Sinai. At the table, the night before his death, he says the sentence in the first person and does not change the pronouns: *if ye love ME, keep MY commandments.* Either he is quoting Sinai's I as his own voice — the Formed, who spoke the words at the mountain — or he is overwriting it. And love-shown-by-keeping-his-commandments is the exact shape the commandment itself gave; the claim and the covenant stand or fall together.$card$, '{"Exodus 20:6"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'exodus' AND c.chapter_number = 20 AND v.verse_number = 6), 'structural', 'Only possible if', 'MY commandments — the ME of Sinai', $card$*If ye love me, keep my commandments.* (John 14:15)

*And shewing mercy unto thousands of them that love me, and keep my commandments.* (Exodus 20:6)

The second commandment describes its own people: *them that love ME, and keep MY commandments* — the me is Yahuah (God) speaking from Sinai. At the table, the night before his death, he says the sentence in the first person and does not change the pronouns: *if ye love ME, keep MY commandments.* Either he is quoting Sinai's I as his own voice — the Formed, who spoke the words at the mountain — or he is overwriting it. And love-shown-by-keeping-his-commandments is the exact shape the commandment itself gave; the claim and the covenant stand or fall together.$card$, '{"Exodus 20:6"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 12 AND v.verse_number = 41), 'structural', 'Only possible if', 'Isaiah saw HIS glory', $card$*These things said Esaias, when he saw his glory, and spake of him.* (John 12:41)

*In the year that king Uzziah died I saw also Yahuah (Lord) sitting upon a throne, high and lifted up, and his train filled the temple.* (Isaiah 6:1)

*Then said I, Woe is me! for I am undone; because I am a man of unclean lips, and I dwell in the midst of a people of unclean lips: for mine eyes have seen the King, Yahuah Tseva'ot (LORD of hosts).* (Isaiah 6:5)

Whose glory did Isaiah see? The prophet's own record says: Yahuah (Lord) on the throne, high and lifted up — *mine eyes have seen the King, Yahuah Tseva'ot (LORD of hosts).* John, writing of Yahusha (Jesus), says *these things said Esaias, when he saw HIS glory, and spake of HIM.* The sentence only works one way: the enthroned King Isaiah saw and the one John follows are one and the same. The throne vision was the Formed — seen, as the Formless never is.$card$, '{"Isaiah 6:1","Isaiah 6:5"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = '1-corinthians' AND c.chapter_number = 10 AND v.verse_number = 4), 'structural', 'Only possible if', 'That Rock was Messiah (Christ)', $card$*And did all drink the same spiritual drink: for they drank of that spiritual Rock that followed them: and that Rock was Messiah (Christ).* (1 Corinthians 10:4)

*Because I will publish the name of Yahuah (LORD): ascribe ye greatness unto our Elohim (God). He is the Rock, his work is perfect: for all his ways are judgment: a Elohim (God) of truth and without iniquity, just and right is he.* (Deuteronomy 32:3-4)

Moses' song leaves no room: *He is the Rock* — the title belongs to Yahuah (LORD) whose name the song publishes. Paul says the Rock that went with the fathers in the wilderness WAS Messiah (Christ). And he presses it further:

*Neither let us tempt Messiah (Christ), as some of them also tempted, and were destroyed of serpents.* (1 Corinthians 10:9)

*And he called the name of the place Massah, and Meribah, because of the chiding of the children of Yashar'el (Israel), and because they tempted Yahuah (LORD), saying, Is Yahuah (LORD) among us, or not?* (Exodus 17:7)

Who was tempted at Massah? The Torah says *they tempted Yahuah (LORD), saying, Is Yahuah (LORD) among us, or not?* Paul says: they tempted Messiah (Christ). The wilderness presence — the Rock, the tempted one, the one among them — was the Formed. Paul's warning to Corinth only makes sense if it is so.$card$, '{"Deuteronomy 32:3-4","Exodus 17:7"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'jude' AND c.chapter_number = 1 AND v.verse_number = 5), 'structural', 'Only possible if', 'The one who saved the people out of Egypt', $card$*I will therefore put you in remembrance, though ye once knew this, how that Yahuah (Lord), having saved the people out of the land of Egypt, afterward destroyed them that believed not.* (Jude 5)

*I am Yahuah Elohayka (the LORD thy God), which have brought thee out of the land of Egypt, out of the house of bondage.* (Exodus 20:2)

Sinai opens with the credential: *I am Yahuah Elohayka (the LORD thy God), which have brought thee out of the land of Egypt.* The exodus is Yahuah (God)'s signature act — the one he names himself by. Jude asks his readers to REMEMBER who saved the people out of Egypt and then judged the unbelieving — and he writes it of the Lord his brother-after-the-flesh served. The Master Jude serves and the Elohim (God) of the exodus are one and the same, or the remembrance fails.$card$, '{"Exodus 20:2"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 1 AND v.verse_number = 18), 'structural', 'Only possible if', 'No man hath seen Elohim (God) — so who was seen?', $card$*No man hath seen Elohim (God) at any time; the only begotten Son, which is in the bosom of the Father, he hath declared him.* (John 1:18)

*And he said, Thou canst not see my face: for there shall no man see me, and live.* (Exodus 33:20)

Two witnesses agree: the Father, the Formless, no man has seen or can see and live. Yet the Torah also records, without blinking:

*And they saw the Elohim (God) of Yashar'el (Israel): and there was under his feet as it were a paved work of a sapphire stone, and as it were the body of heaven in his clearness.* (Exodus 24:10)

They SAW the Elohim (God) of Yashar'el (Israel) — and ate and drank. The canon does not contradict itself; it distinguishes. The Formless no eye beholds; the Formed — the Word, the only begotten in the bosom of the Father — is the one who was seen at the mountain, who declared him, and who could later say:

*Yahusha (Jesus) saith unto him, Have I been so long time with you, and yet hast thou not known me, Philip? he that hath seen me hath seen the Father; and how sayest thou then, Shew us the Father?* (John 14:9)

Every appearance of Elohim (God) in the Tanakh — seen, heard, wrestled with, eaten with — was him. That is what *he hath declared him* has always meant.$card$, '{"Exodus 33:20","Exodus 24:10","John 14:9"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'john' AND c.chapter_number = 19 AND v.verse_number = 37), 'structural', 'Only possible if', 'They shall look upon ME whom they have pierced', $card$*And again another scripture saith, They shall look on him whom they pierced.* (John 19:37)

*And I will pour upon the house of David, and upon the inhabitants of Jerusalem, the spirit of grace and of supplications: and they shall look upon me whom they have pierced, and they shall mourn for him, as one mourneth for his only son, and shall be in bitterness for him, as one that is in bitterness for his firstborn.* (Zechariah 12:10)

Read Zechariah's pronouns slowly. The speaker is Yahuah (LORD) — and he says *they shall look upon ME whom they have PIERCED, and they shall mourn for HIM.* Me, pierced; him, mourned — both in one breath, centuries before the spear. John stands at the cross and says this is that scripture. And the canon's last book seals it:

*Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him: and all kindreds of the earth shall wail because of him. Even so, Amen.* (Revelation 1:7)

Yahuah (LORD) said *me.* The spear found flesh. The verse was only ever possible if the pierced one is the speaker — the Formed, Yahuah (God) come in the flesh, mourned as a firstborn son.$card$, '{"Zechariah 12:10","Revelation 1:7"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'zechariah' AND c.chapter_number = 12 AND v.verse_number = 10), 'structural', 'Only possible if', 'They shall look upon ME whom they have pierced', $card$*And again another scripture saith, They shall look on him whom they pierced.* (John 19:37)

*And I will pour upon the house of David, and upon the inhabitants of Jerusalem, the spirit of grace and of supplications: and they shall look upon me whom they have pierced, and they shall mourn for him, as one mourneth for his only son, and shall be in bitterness for him, as one that is in bitterness for his firstborn.* (Zechariah 12:10)

Read Zechariah's pronouns slowly. The speaker is Yahuah (LORD) — and he says *they shall look upon ME whom they have PIERCED, and they shall mourn for HIM.* Me, pierced; him, mourned — both in one breath, centuries before the spear. John stands at the cross and says this is that scripture. And the canon's last book seals it:

*Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him: and all kindreds of the earth shall wail because of him. Even so, Amen.* (Revelation 1:7)

Yahuah (LORD) said *me.* The spear found flesh. The verse was only ever possible if the pierced one is the speaker — the Formed, Yahuah (God) come in the flesh, mourned as a firstborn son.$card$, '{"Zechariah 12:10","Revelation 1:7"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'mark' AND c.chapter_number = 12 AND v.verse_number = 36), 'structural', 'Only possible if', 'Yahuah (LORD) said unto my Lord', $card$*And Yahusha (Jesus) answered and said, while he taught in the temple, How say the scribes that Messiah (Christ) is the Son of David? For David himself said by the Ruach HaKodesh (Holy Spirit), Yahuah (LORD) said to my Lord, Sit thou on my right hand, till I make thine enemies thy footstool. David therefore himself calleth him Yahuah (Lord); and whence is he then his son? And the common people heard him gladly.* (Mark 12:35-37)

*Yahuah (LORD) said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.* (Psalm 110:1)

His own riddle to the scribes, left hanging in the temple air. David, king of Yashar'el (Israel), bows to no man — yet by the Ruach HaKodesh (Holy Spirit) he calls someone *my Lord,* seated at the right hand of Yahuah (LORD). Whom does a king call Lord? Not a son who is merely a son. The psalm holds two — Yahuah (LORD) who speaks, and David's Lord who sits — the Formless and the Formed, in one verse, a thousand years early. *And the common people heard him gladly.*$card$, '{"Psalm 110:1"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

INSERT INTO red_pill_verses (verse_id, claim_class, class_label, card_title, card_md, anchor_refs, tier_required, last_reviewed_at)
VALUES ((SELECT v.id FROM verses v JOIN chapters c ON c.id = v.chapter_id JOIN books b ON b.id = c.book_id JOIN editions e ON e.id = b.edition_id WHERE e.slug = 'canon' AND b.slug = 'psalms' AND c.chapter_number = 110 AND v.verse_number = 1), 'structural', 'Only possible if', 'Yahuah (LORD) said unto my Lord', $card$*And Yahusha (Jesus) answered and said, while he taught in the temple, How say the scribes that Messiah (Christ) is the Son of David? For David himself said by the Ruach HaKodesh (Holy Spirit), Yahuah (LORD) said to my Lord, Sit thou on my right hand, till I make thine enemies thy footstool. David therefore himself calleth him Yahuah (Lord); and whence is he then his son? And the common people heard him gladly.* (Mark 12:35-37)

*Yahuah (LORD) said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.* (Psalm 110:1)

His own riddle to the scribes, left hanging in the temple air. David, king of Yashar'el (Israel), bows to no man — yet by the Ruach HaKodesh (Holy Spirit) he calls someone *my Lord,* seated at the right hand of Yahuah (LORD). Whom does a king call Lord? Not a son who is merely a son. The psalm holds two — Yahuah (LORD) who speaks, and David's Lord who sits — the Formless and the Formed, in one verse, a thousand years early. *And the common people heard him gladly.*$card$, '{"Psalm 110:1"}'::TEXT[], 'free', NOW())
ON CONFLICT (verse_id) DO UPDATE SET
    claim_class = EXCLUDED.claim_class,
    class_label = EXCLUDED.class_label,
    card_title = EXCLUDED.card_title,
    card_md = EXCLUDED.card_md,
    anchor_refs = EXCLUDED.anchor_refs,
    last_reviewed_at = NOW(),
    updated_at = NOW();

DO $verify$
DECLARE
    n INT;
BEGIN
    SELECT COUNT(*) INTO n FROM red_pill_verses;
    IF n < 39 THEN
        RAISE EXCEPTION 'session204 seed verify failed: % rows (expected >= 39)', n;
    END IF;
    RAISE NOTICE 'session204 seed verified: % witness verses live.', n;
END
$verify$;

COMMIT;
