-- =====================================================================
-- Session 424 migration — 2026-07-12
-- NT sacred-name sweep: 239 verses where the pipeline rendered the Father's
-- name "Yahuah (Lord)" in a place the Master Yahusha is meant (S182 NT-Lord
-- convention + Yoshi's 2026-07-11 decision; Strong's-tag tie-break applied).
--   * Master's TITLE  "Lord"      -> "Adonai (Lord)"   (83 verses)
--   * standalone/narrative "Lord" -> "Yahusha (Lord)"  (135 verses)
--   * human / parable master      -> "Lord" (English)  (13 verses)
--   * positional (two referents in one verse)          (8 verses)
-- The 79 AMBIGUOUS verses (Father-vs-Master, contextual) are DELIBERATELY
-- NOT touched here — Yoshi's call, another day. Section B (stays Yahuah) and
-- 1 Cor 12:3 (exempt) are likewise untouched.
--
-- Keyed by editions.slug='canon' -> books.slug -> chapters.chapter_number
-- -> verses.verse_number, updating verses.text (the reader-UI column).
-- Parenthetical-agnostic REPLACE on the sacred-name token only (same design
-- as session423), so it applies regardless of DB parenthetical drift and is
-- idempotent (re-run matches the already-corrected token and is a no-op).
--
-- Run in the Render remnant-app-api Shell (cwd /app):
--   python3 apply_migration.py /data-schema/migrations/session424_nt_master_sweep.sql
-- =====================================================================

BEGIN;

DO $before$
DECLARE s TEXT;
BEGIN
  SELECT v.text INTO s FROM verses v
    JOIN chapters c ON c.id=v.chapter_id AND c.chapter_number=5
    JOIN books b ON b.id=c.book_id AND b.slug='galatians'
    JOIN editions e ON e.id=b.edition_id AND e.slug='canon'
   WHERE v.verse_number=10;
  RAISE NOTICE 'S424 BEFORE Gal 5:10 : %', s;
END $before$;

-- ---------------------------------------------------------------------
-- GROUP A — Master title -> Adonai: 83 verses  (Yahuah (Lord) -> Adonai (Lord))
-- ---------------------------------------------------------------------
UPDATE verses v
   SET text = REPLACE(REPLACE(REPLACE(REPLACE(v.text,
                   'Yahuah''s (Lord’s)','Adonai''s (Lord’s)'),
                   'Yahuah''s (Lord''s)','Adonai''s (Lord''s)'),
                   'Yahuah (the Lord)','Adonai (the Lord)'),
                   'Yahuah (Lord)','Adonai (Lord)')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id    AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
  JOIN (VALUES
        ('1-corinthians',2,8),
        ('1-corinthians',12,5),
        ('1-corinthians',15,47),
        ('2-corinthians',4,5),
        ('2-peter',2,20),
        ('2-peter',3,2),
        ('acts',1,6),
        ('acts',7,60),
        ('acts',9,13),
        ('acts',10,36),
        ('acts',22,8),
        ('acts',22,19),
        ('acts',26,15),
        ('colossians',2,6),
        ('ephesians',4,5),
        ('james',2,1),
        ('john',11,3),
        ('john',11,12),
        ('john',11,21),
        ('john',11,32),
        ('john',11,34),
        ('john',11,39),
        ('john',13,6),
        ('john',13,9),
        ('john',13,25),
        ('john',13,36),
        ('john',13,37),
        ('john',14,8),
        ('john',14,22),
        ('john',21,15),
        ('john',21,16),
        ('john',21,17),
        ('john',21,20),
        ('john',21,21),
        ('luke',2,11),
        ('luke',5,8),
        ('luke',5,12),
        ('luke',6,5),
        ('luke',6,46),
        ('luke',7,6),
        ('luke',9,57),
        ('luke',9,59),
        ('luke',9,61),
        ('luke',10,17),
        ('luke',12,41),
        ('luke',13,23),
        ('luke',13,25),
        ('luke',17,37),
        ('luke',18,41),
        ('luke',20,44),
        ('luke',22,33),
        ('luke',22,38),
        ('luke',23,42),
        ('mark',2,28),
        ('mark',7,28),
        ('mark',9,24),
        ('mark',10,51),
        ('mark',12,37),
        ('matthew',7,21),
        ('matthew',7,22),
        ('matthew',8,2),
        ('matthew',8,6),
        ('matthew',8,8),
        ('matthew',8,21),
        ('matthew',9,28),
        ('matthew',12,8),
        ('matthew',13,51),
        ('matthew',15,22),
        ('matthew',15,25),
        ('matthew',15,27),
        ('matthew',16,22),
        ('matthew',17,15),
        ('matthew',18,21),
        ('matthew',20,30),
        ('matthew',20,31),
        ('matthew',20,33),
        ('matthew',22,43),
        ('matthew',22,45),
        ('matthew',25,11),
        ('matthew',25,37),
        ('matthew',25,44),
        ('matthew',26,22),
        ('romans',14,9)
       ) AS t(bslug, ch, vs) ON b.slug = t.bslug AND c.chapter_number = t.ch AND v.verse_number = t.vs
 WHERE v.chapter_id = c.id;

-- ---------------------------------------------------------------------
-- GROUP B — standalone/narrative -> Yahusha: 135 verses  (Yahuah (Lord) -> Yahusha (Lord))
-- ---------------------------------------------------------------------
UPDATE verses v
   SET text = REPLACE(REPLACE(REPLACE(REPLACE(v.text,
                   'Yahuah''s (Lord’s)','Yahusha''s (Lord’s)'),
                   'Yahuah''s (Lord''s)','Yahusha''s (Lord''s)'),
                   'Yahuah (the Lord)','Yahusha (the Lord)'),
                   'Yahuah (Lord)','Yahusha (Lord)')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id    AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
  JOIN (VALUES
        ('1-corinthians',4,4),
        ('1-corinthians',4,5),
        ('1-corinthians',4,17),
        ('1-corinthians',6,13),
        ('1-corinthians',6,14),
        ('1-corinthians',6,17),
        ('1-corinthians',7,10),
        ('1-corinthians',7,12),
        ('1-corinthians',7,22),
        ('1-corinthians',7,25),
        ('1-corinthians',7,32),
        ('1-corinthians',7,34),
        ('1-corinthians',7,35),
        ('1-corinthians',7,39),
        ('1-corinthians',9,1),
        ('1-corinthians',9,2),
        ('1-corinthians',9,5),
        ('1-corinthians',9,14),
        ('1-corinthians',10,21),
        ('1-corinthians',11,11),
        ('1-corinthians',15,58),
        ('1-corinthians',16,10),
        ('1-corinthians',16,19),
        ('1-peter',2,13),
        ('1-thessalonians',1,6),
        ('1-thessalonians',3,8),
        ('1-thessalonians',3,12),
        ('1-thessalonians',4,15),
        ('1-thessalonians',4,16),
        ('1-thessalonians',4,17),
        ('1-thessalonians',5,12),
        ('1-thessalonians',5,27),
        ('2-corinthians',5,6),
        ('2-corinthians',5,8),
        ('2-corinthians',5,11),
        ('2-corinthians',10,8),
        ('2-corinthians',11,17),
        ('2-corinthians',12,1),
        ('2-corinthians',12,8),
        ('2-corinthians',13,10),
        ('2-peter',2,1),
        ('2-thessalonians',2,8),
        ('2-thessalonians',3,3),
        ('2-thessalonians',3,4),
        ('2-thessalonians',3,5),
        ('2-timothy',1,16),
        ('2-timothy',1,18),
        ('2-timothy',2,7),
        ('2-timothy',2,14),
        ('2-timothy',2,22),
        ('2-timothy',2,24),
        ('2-timothy',3,11),
        ('2-timothy',4,8),
        ('2-timothy',4,17),
        ('2-timothy',4,18),
        ('acts',9,1),
        ('acts',9,11),
        ('acts',9,15),
        ('acts',9,17),
        ('acts',9,27),
        ('acts',10,48),
        ('acts',11,16),
        ('acts',18,9),
        ('acts',23,11),
        ('colossians',1,10),
        ('colossians',3,16),
        ('colossians',3,18),
        ('colossians',3,20),
        ('colossians',3,23),
        ('colossians',4,7),
        ('colossians',4,17),
        ('ephesians',2,21),
        ('ephesians',4,1),
        ('ephesians',4,17),
        ('ephesians',5,8),
        ('ephesians',5,10),
        ('ephesians',5,19),
        ('ephesians',5,22),
        ('ephesians',5,29),
        ('ephesians',6,1),
        ('ephesians',6,4),
        ('ephesians',6,7),
        ('ephesians',6,8),
        ('ephesians',6,10),
        ('ephesians',6,21),
        ('galatians',5,10),
        ('hebrews',2,3),
        ('james',5,7),
        ('james',5,8),
        ('john',4,1),
        ('john',6,23),
        ('john',11,2),
        ('john',20,2),
        ('john',20,18),
        ('john',20,20),
        ('john',20,25),
        ('john',21,7),
        ('john',21,12),
        ('luke',7,13),
        ('luke',7,31),
        ('luke',10,1),
        ('luke',11,39),
        ('luke',12,42),
        ('luke',13,15),
        ('luke',17,6),
        ('luke',18,6),
        ('luke',19,31),
        ('luke',19,34),
        ('luke',22,31),
        ('luke',24,34),
        ('mark',11,3),
        ('mark',16,19),
        ('mark',16,20),
        ('matthew',21,3),
        ('matthew',28,6),
        ('philemon',1,16),
        ('philemon',1,20),
        ('philippians',1,14),
        ('philippians',2,24),
        ('philippians',2,29),
        ('philippians',3,1),
        ('philippians',4,1),
        ('philippians',4,2),
        ('philippians',4,4),
        ('philippians',4,5),
        ('philippians',4,10),
        ('revelation',14,13),
        ('romans',14,6),
        ('romans',14,8),
        ('romans',16,2),
        ('romans',16,8),
        ('romans',16,11),
        ('romans',16,12),
        ('romans',16,13),
        ('romans',16,22)
       ) AS t(bslug, ch, vs) ON b.slug = t.bslug AND c.chapter_number = t.ch AND v.verse_number = t.vs
 WHERE v.chapter_id = c.id;

-- ---------------------------------------------------------------------
-- GROUP C — human/parable master -> English Lord: 13 verses  (Yahuah (Lord) -> Lord (Lord))
-- ---------------------------------------------------------------------
UPDATE verses v
   SET text = REPLACE(REPLACE(REPLACE(REPLACE(v.text,
                   'Yahuah''s (Lord’s)','Lord’s'),
                   'Yahuah''s (Lord''s)','Lord''s'),
                   'Yahuah (the Lord)','the Lord'),
                   'Yahuah (Lord)','Lord')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id    AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
  JOIN (VALUES
        ('john',6,34),
        ('john',8,11),
        ('john',9,36),
        ('luke',13,8),
        ('luke',14,22),
        ('luke',19,16),
        ('luke',19,18),
        ('luke',19,20),
        ('luke',19,25),
        ('matthew',18,26),
        ('matthew',25,20),
        ('matthew',25,22),
        ('matthew',25,24)
       ) AS t(bslug, ch, vs) ON b.slug = t.bslug AND c.chapter_number = t.ch AND v.verse_number = t.vs
 WHERE v.chapter_id = c.id;

-- ---------------------------------------------------------------------
-- GROUP D — positional (two referents in one verse), context-anchored
-- ---------------------------------------------------------------------
-- 2 Thessalonians 3:16  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'Now Yahuah (Lord) of peace','Now Adonai (Lord) of peace'),
                   'Yahuah (Lord) be with you all','Yahusha (Lord) be with you all')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='2-thessalonians' AND c.chapter_number=3 AND v.verse_number=16;

-- Acts 9:5  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'thou, Yahuah (Lord)?','thou, Adonai (Lord)?'),
                   'And Yahuah (Lord) said','And Yahusha (Lord) said')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='acts' AND c.chapter_number=9 AND v.verse_number=5;

-- Acts 9:6  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'said, Yahuah (Lord), what wilt thou','said, Adonai (Lord), what wilt thou'),
                   'And Yahuah (Lord) said unto him','And Yahusha (Lord) said unto him')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='acts' AND c.chapter_number=9 AND v.verse_number=6;

-- Acts 9:10  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'said Yahuah (Lord) in a vision','said Yahusha (Lord) in a vision'),
                   'I am here, Yahuah (Lord)','I am here, Adonai (Lord)')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='acts' AND c.chapter_number=9 AND v.verse_number=10;

-- Acts 22:10  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'do, Yahuah (Lord)?','do, Adonai (Lord)?'),
                   'And Yahuah (Lord) said unto me','And Yahusha (Lord) said unto me')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='acts' AND c.chapter_number=22 AND v.verse_number=10;

-- Colossians 3:24  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'of Yahuah (Lord) ye shall','of Yahusha (Lord) ye shall'),
                   'ye serve Yahuah (Lord) Messiah','ye serve Adonai (Lord) Messiah')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='colossians' AND c.chapter_number=3 AND v.verse_number=24;

-- Luke 19:8  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'said unto Yahuah (Lord);','said unto Yahusha (Lord);'),
                   'Behold, Yahuah (Lord), the half','Behold, Adonai (Lord), the half')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='luke' AND c.chapter_number=19 AND v.verse_number=8;

-- Luke 22:61  (positional: two occurrences resolved by context)
UPDATE verses v
   SET text = REPLACE(REPLACE(v.text,
                   'And Yahuah (Lord) turned','And Yahusha (Lord) turned'),
                   'the word of Yahuah (Lord)','the word of Yahusha (Lord)')
  FROM chapters c
  JOIN books    b ON b.id = c.book_id AND b.edition_id = (SELECT id FROM editions WHERE slug='canon')
 WHERE v.chapter_id = c.id AND b.slug='luke' AND c.chapter_number=22 AND v.verse_number=61;

-- ---------------------------------------------------------------------
-- VERIFY: every one of the 239 target verses exists and now carries NO
-- Master-for-Father token; fail loudly otherwise. Idempotent-safe.
-- ---------------------------------------------------------------------
DO $verify$
DECLARE found INT; residual INT;
BEGIN
  WITH targets(bslug,ch,vs) AS (VALUES
        ('1-corinthians',2,8),
        ('1-corinthians',4,4),
        ('1-corinthians',4,5),
        ('1-corinthians',4,17),
        ('1-corinthians',6,13),
        ('1-corinthians',6,14),
        ('1-corinthians',6,17),
        ('1-corinthians',7,10),
        ('1-corinthians',7,12),
        ('1-corinthians',7,22),
        ('1-corinthians',7,25),
        ('1-corinthians',7,32),
        ('1-corinthians',7,34),
        ('1-corinthians',7,35),
        ('1-corinthians',7,39),
        ('1-corinthians',9,1),
        ('1-corinthians',9,2),
        ('1-corinthians',9,5),
        ('1-corinthians',9,14),
        ('1-corinthians',10,21),
        ('1-corinthians',11,11),
        ('1-corinthians',12,5),
        ('1-corinthians',15,47),
        ('1-corinthians',15,58),
        ('1-corinthians',16,10),
        ('1-corinthians',16,19),
        ('1-peter',2,13),
        ('1-thessalonians',1,6),
        ('1-thessalonians',3,8),
        ('1-thessalonians',3,12),
        ('1-thessalonians',4,15),
        ('1-thessalonians',4,16),
        ('1-thessalonians',4,17),
        ('1-thessalonians',5,12),
        ('1-thessalonians',5,27),
        ('2-corinthians',4,5),
        ('2-corinthians',5,6),
        ('2-corinthians',5,8),
        ('2-corinthians',5,11),
        ('2-corinthians',10,8),
        ('2-corinthians',11,17),
        ('2-corinthians',12,1),
        ('2-corinthians',12,8),
        ('2-corinthians',13,10),
        ('2-peter',2,1),
        ('2-peter',2,20),
        ('2-peter',3,2),
        ('2-thessalonians',2,8),
        ('2-thessalonians',3,3),
        ('2-thessalonians',3,4),
        ('2-thessalonians',3,5),
        ('2-thessalonians',3,16),
        ('2-timothy',1,16),
        ('2-timothy',1,18),
        ('2-timothy',2,7),
        ('2-timothy',2,14),
        ('2-timothy',2,22),
        ('2-timothy',2,24),
        ('2-timothy',3,11),
        ('2-timothy',4,8),
        ('2-timothy',4,17),
        ('2-timothy',4,18),
        ('acts',1,6),
        ('acts',7,60),
        ('acts',9,1),
        ('acts',9,5),
        ('acts',9,6),
        ('acts',9,10),
        ('acts',9,11),
        ('acts',9,13),
        ('acts',9,15),
        ('acts',9,17),
        ('acts',9,27),
        ('acts',10,36),
        ('acts',10,48),
        ('acts',11,16),
        ('acts',18,9),
        ('acts',22,8),
        ('acts',22,10),
        ('acts',22,19),
        ('acts',23,11),
        ('acts',26,15),
        ('colossians',1,10),
        ('colossians',2,6),
        ('colossians',3,16),
        ('colossians',3,18),
        ('colossians',3,20),
        ('colossians',3,23),
        ('colossians',3,24),
        ('colossians',4,7),
        ('colossians',4,17),
        ('ephesians',2,21),
        ('ephesians',4,1),
        ('ephesians',4,5),
        ('ephesians',4,17),
        ('ephesians',5,8),
        ('ephesians',5,10),
        ('ephesians',5,19),
        ('ephesians',5,22),
        ('ephesians',5,29),
        ('ephesians',6,1),
        ('ephesians',6,4),
        ('ephesians',6,7),
        ('ephesians',6,8),
        ('ephesians',6,10),
        ('ephesians',6,21),
        ('galatians',5,10),
        ('hebrews',2,3),
        ('james',2,1),
        ('james',5,7),
        ('james',5,8),
        ('john',4,1),
        ('john',6,23),
        ('john',6,34),
        ('john',8,11),
        ('john',9,36),
        ('john',11,2),
        ('john',11,3),
        ('john',11,12),
        ('john',11,21),
        ('john',11,32),
        ('john',11,34),
        ('john',11,39),
        ('john',13,6),
        ('john',13,9),
        ('john',13,25),
        ('john',13,36),
        ('john',13,37),
        ('john',14,8),
        ('john',14,22),
        ('john',20,2),
        ('john',20,18),
        ('john',20,20),
        ('john',20,25),
        ('john',21,7),
        ('john',21,12),
        ('john',21,15),
        ('john',21,16),
        ('john',21,17),
        ('john',21,20),
        ('john',21,21),
        ('luke',2,11),
        ('luke',5,8),
        ('luke',5,12),
        ('luke',6,5),
        ('luke',6,46),
        ('luke',7,6),
        ('luke',7,13),
        ('luke',7,31),
        ('luke',9,57),
        ('luke',9,59),
        ('luke',9,61),
        ('luke',10,1),
        ('luke',10,17),
        ('luke',11,39),
        ('luke',12,41),
        ('luke',12,42),
        ('luke',13,8),
        ('luke',13,15),
        ('luke',13,23),
        ('luke',13,25),
        ('luke',14,22),
        ('luke',17,6),
        ('luke',17,37),
        ('luke',18,6),
        ('luke',18,41),
        ('luke',19,8),
        ('luke',19,16),
        ('luke',19,18),
        ('luke',19,20),
        ('luke',19,25),
        ('luke',19,31),
        ('luke',19,34),
        ('luke',20,44),
        ('luke',22,31),
        ('luke',22,33),
        ('luke',22,38),
        ('luke',22,61),
        ('luke',23,42),
        ('luke',24,34),
        ('mark',2,28),
        ('mark',7,28),
        ('mark',9,24),
        ('mark',10,51),
        ('mark',11,3),
        ('mark',12,37),
        ('mark',16,19),
        ('mark',16,20),
        ('matthew',7,21),
        ('matthew',7,22),
        ('matthew',8,2),
        ('matthew',8,6),
        ('matthew',8,8),
        ('matthew',8,21),
        ('matthew',9,28),
        ('matthew',12,8),
        ('matthew',13,51),
        ('matthew',15,22),
        ('matthew',15,25),
        ('matthew',15,27),
        ('matthew',16,22),
        ('matthew',17,15),
        ('matthew',18,21),
        ('matthew',18,26),
        ('matthew',20,30),
        ('matthew',20,31),
        ('matthew',20,33),
        ('matthew',21,3),
        ('matthew',22,43),
        ('matthew',22,45),
        ('matthew',25,11),
        ('matthew',25,20),
        ('matthew',25,22),
        ('matthew',25,24),
        ('matthew',25,37),
        ('matthew',25,44),
        ('matthew',26,22),
        ('matthew',28,6),
        ('philemon',1,16),
        ('philemon',1,20),
        ('philippians',1,14),
        ('philippians',2,24),
        ('philippians',2,29),
        ('philippians',3,1),
        ('philippians',4,1),
        ('philippians',4,2),
        ('philippians',4,4),
        ('philippians',4,5),
        ('philippians',4,10),
        ('revelation',14,13),
        ('romans',14,6),
        ('romans',14,8),
        ('romans',14,9),
        ('romans',16,2),
        ('romans',16,8),
        ('romans',16,11),
        ('romans',16,12),
        ('romans',16,13),
        ('romans',16,22)
  )
  SELECT count(*) INTO found
    FROM targets t
    JOIN editions e ON e.slug='canon'
    JOIN books    b ON b.edition_id=e.id AND b.slug=t.bslug
    JOIN chapters c ON c.book_id=b.id AND c.chapter_number=t.ch
    JOIN verses   v ON v.chapter_id=c.id AND v.verse_number=t.vs;
  IF found <> 239 THEN
     RAISE EXCEPTION 'S424: expected 239 canon target verses, found %', found;
  END IF;

  WITH targets(bslug,ch,vs) AS (VALUES
        ('1-corinthians',2,8),
        ('1-corinthians',4,4),
        ('1-corinthians',4,5),
        ('1-corinthians',4,17),
        ('1-corinthians',6,13),
        ('1-corinthians',6,14),
        ('1-corinthians',6,17),
        ('1-corinthians',7,10),
        ('1-corinthians',7,12),
        ('1-corinthians',7,22),
        ('1-corinthians',7,25),
        ('1-corinthians',7,32),
        ('1-corinthians',7,34),
        ('1-corinthians',7,35),
        ('1-corinthians',7,39),
        ('1-corinthians',9,1),
        ('1-corinthians',9,2),
        ('1-corinthians',9,5),
        ('1-corinthians',9,14),
        ('1-corinthians',10,21),
        ('1-corinthians',11,11),
        ('1-corinthians',12,5),
        ('1-corinthians',15,47),
        ('1-corinthians',15,58),
        ('1-corinthians',16,10),
        ('1-corinthians',16,19),
        ('1-peter',2,13),
        ('1-thessalonians',1,6),
        ('1-thessalonians',3,8),
        ('1-thessalonians',3,12),
        ('1-thessalonians',4,15),
        ('1-thessalonians',4,16),
        ('1-thessalonians',4,17),
        ('1-thessalonians',5,12),
        ('1-thessalonians',5,27),
        ('2-corinthians',4,5),
        ('2-corinthians',5,6),
        ('2-corinthians',5,8),
        ('2-corinthians',5,11),
        ('2-corinthians',10,8),
        ('2-corinthians',11,17),
        ('2-corinthians',12,1),
        ('2-corinthians',12,8),
        ('2-corinthians',13,10),
        ('2-peter',2,1),
        ('2-peter',2,20),
        ('2-peter',3,2),
        ('2-thessalonians',2,8),
        ('2-thessalonians',3,3),
        ('2-thessalonians',3,4),
        ('2-thessalonians',3,5),
        ('2-thessalonians',3,16),
        ('2-timothy',1,16),
        ('2-timothy',1,18),
        ('2-timothy',2,7),
        ('2-timothy',2,14),
        ('2-timothy',2,22),
        ('2-timothy',2,24),
        ('2-timothy',3,11),
        ('2-timothy',4,8),
        ('2-timothy',4,17),
        ('2-timothy',4,18),
        ('acts',1,6),
        ('acts',7,60),
        ('acts',9,1),
        ('acts',9,5),
        ('acts',9,6),
        ('acts',9,10),
        ('acts',9,11),
        ('acts',9,13),
        ('acts',9,15),
        ('acts',9,17),
        ('acts',9,27),
        ('acts',10,36),
        ('acts',10,48),
        ('acts',11,16),
        ('acts',18,9),
        ('acts',22,8),
        ('acts',22,10),
        ('acts',22,19),
        ('acts',23,11),
        ('acts',26,15),
        ('colossians',1,10),
        ('colossians',2,6),
        ('colossians',3,16),
        ('colossians',3,18),
        ('colossians',3,20),
        ('colossians',3,23),
        ('colossians',3,24),
        ('colossians',4,7),
        ('colossians',4,17),
        ('ephesians',2,21),
        ('ephesians',4,1),
        ('ephesians',4,5),
        ('ephesians',4,17),
        ('ephesians',5,8),
        ('ephesians',5,10),
        ('ephesians',5,19),
        ('ephesians',5,22),
        ('ephesians',5,29),
        ('ephesians',6,1),
        ('ephesians',6,4),
        ('ephesians',6,7),
        ('ephesians',6,8),
        ('ephesians',6,10),
        ('ephesians',6,21),
        ('galatians',5,10),
        ('hebrews',2,3),
        ('james',2,1),
        ('james',5,7),
        ('james',5,8),
        ('john',4,1),
        ('john',6,23),
        ('john',6,34),
        ('john',8,11),
        ('john',9,36),
        ('john',11,2),
        ('john',11,3),
        ('john',11,12),
        ('john',11,21),
        ('john',11,32),
        ('john',11,34),
        ('john',11,39),
        ('john',13,6),
        ('john',13,9),
        ('john',13,25),
        ('john',13,36),
        ('john',13,37),
        ('john',14,8),
        ('john',14,22),
        ('john',20,2),
        ('john',20,18),
        ('john',20,20),
        ('john',20,25),
        ('john',21,7),
        ('john',21,12),
        ('john',21,15),
        ('john',21,16),
        ('john',21,17),
        ('john',21,20),
        ('john',21,21),
        ('luke',2,11),
        ('luke',5,8),
        ('luke',5,12),
        ('luke',6,5),
        ('luke',6,46),
        ('luke',7,6),
        ('luke',7,13),
        ('luke',7,31),
        ('luke',9,57),
        ('luke',9,59),
        ('luke',9,61),
        ('luke',10,1),
        ('luke',10,17),
        ('luke',11,39),
        ('luke',12,41),
        ('luke',12,42),
        ('luke',13,8),
        ('luke',13,15),
        ('luke',13,23),
        ('luke',13,25),
        ('luke',14,22),
        ('luke',17,6),
        ('luke',17,37),
        ('luke',18,6),
        ('luke',18,41),
        ('luke',19,8),
        ('luke',19,16),
        ('luke',19,18),
        ('luke',19,20),
        ('luke',19,25),
        ('luke',19,31),
        ('luke',19,34),
        ('luke',20,44),
        ('luke',22,31),
        ('luke',22,33),
        ('luke',22,38),
        ('luke',22,61),
        ('luke',23,42),
        ('luke',24,34),
        ('mark',2,28),
        ('mark',7,28),
        ('mark',9,24),
        ('mark',10,51),
        ('mark',11,3),
        ('mark',12,37),
        ('mark',16,19),
        ('mark',16,20),
        ('matthew',7,21),
        ('matthew',7,22),
        ('matthew',8,2),
        ('matthew',8,6),
        ('matthew',8,8),
        ('matthew',8,21),
        ('matthew',9,28),
        ('matthew',12,8),
        ('matthew',13,51),
        ('matthew',15,22),
        ('matthew',15,25),
        ('matthew',15,27),
        ('matthew',16,22),
        ('matthew',17,15),
        ('matthew',18,21),
        ('matthew',18,26),
        ('matthew',20,30),
        ('matthew',20,31),
        ('matthew',20,33),
        ('matthew',21,3),
        ('matthew',22,43),
        ('matthew',22,45),
        ('matthew',25,11),
        ('matthew',25,20),
        ('matthew',25,22),
        ('matthew',25,24),
        ('matthew',25,37),
        ('matthew',25,44),
        ('matthew',26,22),
        ('matthew',28,6),
        ('philemon',1,16),
        ('philemon',1,20),
        ('philippians',1,14),
        ('philippians',2,24),
        ('philippians',2,29),
        ('philippians',3,1),
        ('philippians',4,1),
        ('philippians',4,2),
        ('philippians',4,4),
        ('philippians',4,5),
        ('philippians',4,10),
        ('revelation',14,13),
        ('romans',14,6),
        ('romans',14,8),
        ('romans',14,9),
        ('romans',16,2),
        ('romans',16,8),
        ('romans',16,11),
        ('romans',16,12),
        ('romans',16,13),
        ('romans',16,22)
  )
  SELECT count(*) INTO residual
    FROM targets t
    JOIN editions e ON e.slug='canon'
    JOIN books    b ON b.edition_id=e.id AND b.slug=t.bslug
    JOIN chapters c ON c.book_id=b.id AND c.chapter_number=t.ch
    JOIN verses   v ON v.chapter_id=c.id AND v.verse_number=t.vs
   WHERE v.text LIKE '%Yahuah (Lord)%'
      OR v.text LIKE '%Yahuah (the Lord)%'
      OR v.text LIKE '%Yahuah''s (Lord%';
  IF residual <> 0 THEN
     RAISE EXCEPTION 'S424: % target verses still carry a Master-for-Father Yahuah token', residual;
  END IF;

  RAISE NOTICE 'S424 OK: 239 target verses corrected; 0 residual Master-for-Father tokens.';
END $verify$;

COMMIT;
