-- =====================================================================
-- Session 204 migration — 2026-06-06
-- =====================================================================
-- THE WITNESS (working title: the Red Pill) — the inverted red-letter
-- overlay. Red-letter editions mark where the Messiah speaks; the
-- Witness marks every verse where he — or anyone speaking of him —
-- claims to be Yahuah, plus every verse that is only possible if he is
-- the one who spoke to Moses and the prophets.
--
-- Engine: the TRANSFER TEST (Yoshi, S203 close). Every member verse
-- passes one test — the NT gives Yahusha (Jesus) a title, an act, or
-- an argument that the Tanakh says belongs to Yahuah ALONE, or that
-- Yahuah said HE HIMSELF would do. Four claim classes:
--   direct     — deity claims from his own mouth or those speaking of him
--   title      — Yahuah's own titles claimed (Good Shepherd ↔ Ezekiel 34)
--   act        — acts the Tanakh ascribes to Yahuah alone (Luke 21 ↔ Zech 14)
--   structural — arguments only possible if he is the Yahuah of Sinai
--                (Romans 7:1-4 first-husband-died; John 14:15 ↔ Exodus 20:6)
--
-- Decisions locked at S204 open (Yoshi):
--   ONE mark for all four classes (the class lives on the card).
--   FREE — the proclamation surface; no tier gate, ever (tier_required
--     kept for schema uniformity; default 'free' and expected to stay).
--   Full-canon V1 (Tanakh anchors carry the mark too); extras wave 2.
--   Reader-facing name "The Witness"; Red Pill is the working title.
--   Mark register: dedicated "witness red" (proof Option B signed off).
--
-- Same curated-overlay shape as cross_reference_threads (S73) and
-- tool_annotations (S196): fixed verse text untouched, keyed overlay
-- beside it, every row checker-gated (Red Line #12, checklist 10,
-- quote-don't-cite, sacred names) before it lands.
--
-- One row per marked verse (one mark — UNIQUE(verse_id)); a verse
-- carrying several claims gets one card that holds them together.
-- card_md is the full come-and-see card: every verse quoted in full,
-- stand-alone italics, citation at the end — the claim and its Tanakh
-- anchor side by side so the reader watches the transfer happen.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + guarded index creation.
-- Seed rows land via session204_red_pill_seed_v1.sql (generated by
-- restoration-pipeline/_session204_build_red_pill_seed.py from
-- canon.json so every quote is exact restored text).
--
-- Run via: python3 api/apply_migration.py data-schema/migrations/session204_red_pill_witness.sql
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS red_pill_verses (
    id              BIGSERIAL PRIMARY KEY,
    verse_id        BIGINT NOT NULL REFERENCES verses(id) ON DELETE CASCADE,
    claim_class     TEXT NOT NULL CHECK (claim_class IN
                        ('direct','title','act','structural')),
    class_label     TEXT NOT NULL,        -- reader-facing tag: 'His own mouth',
                                          -- 'The title transferred', 'The act transferred',
                                          -- 'Only possible if'
    card_title      TEXT NOT NULL,        -- e.g. 'Before Abraham was — I AM'
    card_md         TEXT NOT NULL,        -- full come-and-see card (markdown; every
                                          -- verse quoted in full, stand-alone italics,
                                          -- citation at the end; sacred names intact)
    anchor_refs     TEXT[] NOT NULL DEFAULT '{}',  -- human-readable refs the card pairs
                                          -- (e.g. {'Exodus 3:14','John 8:59'})
    tier_required   content_tier NOT NULL DEFAULT 'free',
    last_reviewed_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (verse_id)
);

CREATE INDEX IF NOT EXISTS idx_red_pill_verse ON red_pill_verses(verse_id);
CREATE INDEX IF NOT EXISTS idx_red_pill_class ON red_pill_verses(claim_class);

COMMENT ON TABLE red_pill_verses IS
    'THE WITNESS (working title: Red Pill) — the inverted red-letter overlay, S204. One row per verse that passes the transfer test: the NT gives Yahusha (Jesus) a title, act, or argument the Tanakh gives to Yahuah alone, or that Yahuah said he himself would do. Tanakh anchor verses carry the mark too (full-canon V1). card_md is the come-and-see tap-card: both sides quoted in full, stand-alone italics, the Formed/Formless framework carrying every card — no Trinity assumption, no modalism, the inherited view engaged in good faith, never argued down. Every row is checker-gated (Red Line #12 son-of-Adam + kaph-comparative, checklist 10 Nature of God, quote-don''t-cite, sacred names) before it lands. Free tier — the proclamation surface. The surface is PILL-GENERIC by design: the Kingdom (blue pill) rides the same rails next.';

UPDATE schema_version
   SET version   = '1.0.0-phase-sessionD-session204',
       landed_at = NOW(),
       notes     = 'Session 204 — red_pill_verses landed: The Witness (inverted red-letter) curated overlay, transfer-test engine, four claim classes, one mark, free tier, full-canon V1. Seed v1 via session204_red_pill_seed_v1.sql. Prior version: 1.0.0-phase-sessionB-session196 lineage.'
 WHERE id = 1;

DO $verify$
DECLARE
    tbl_exists  BOOLEAN;
    uniq_exists BOOLEAN;
    tier_ok     BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'red_pill_verses'
    ) INTO tbl_exists;

    SELECT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'red_pill_verses'
          AND constraint_type = 'UNIQUE'
    ) INTO uniq_exists;

    SELECT tier_satisfies('free'::content_tier, 'free'::content_tier)
      INTO tier_ok;

    IF NOT tbl_exists OR NOT uniq_exists OR NOT tier_ok THEN
        RAISE EXCEPTION
            'session204 red_pill_verses verify failed: tbl=% uniq=% tier=%',
            tbl_exists, uniq_exists, tier_ok;
    END IF;

    RAISE NOTICE 'session204 red_pill_verses verified: table + unique + indexes landed.';
END
$verify$;

COMMIT;
