-- =====================================================================
-- Session 205 migration — 2026-06-06
-- =====================================================================
-- THE KINGDOM (working title: the Blue Pill) — the companion overlay
-- to the Witness. The Witness marks every verse where the Formed
-- claims the Tanakh's "I"; the Kingdom marks the proclamation itself:
-- every new-testament mention of what the Messiah did, what the good
-- news is, what the kingdom is, what grace is — paired with the
-- scripture it was taught from.
--
-- Engine: the NOTHING-NEW TEST (Yoshi, S205 open). Nothing in the new
-- testament is new. Every teaching and concept is found in the source
-- it was taught from; every beginning declared the end; every
-- prophecy. "He shall save his people from their sins — where's that
-- recorded?" Five concept strands:
--   gathering — the regathering of the two houses (Ezekiel 37:15-22,
--               the two sticks; Ezekiel 34; Hosea 1-2; John 10:16)
--   good_news — the good tidings themselves (Isaiah 52:7; Isaiah 61
--               ↔ Luke 4:18-21; Mark 1:14-15)
--   kingdom   — the kingdom proclaimed and promised (Daniel 2:44;
--               Daniel 7; Isaiah 9:6-7 ↔ Luke 1:32-33)
--   grace     — grace as the means of return: the new heart, the
--               Torah written within (Exodus 34:6; Jeremiah 31:33;
--               Ezekiel 36:26-27)
--   teaching  — his teachings quoted from their sources (Matthew
--               22:37-40 ↔ Deuteronomy 6:5 + Leviticus 19:18)
--
-- Decisions locked at S205 open (Yoshi):
--   Register: TWO-TONE — the existing metallic emerald + metallic
--     gold joined in one pill, the two sticks of Ezekiel 37:15-22,
--     hard seam, border blend #2EFFA1→#FCECAF ("uniting the old and
--     new testament").
--   In-verse mark: a double quotation mark built from two single
--     quote glyphs — emerald outside, gold inside, both ends of the
--     verse (proof v3 signed off).
--   FREE — the proclamation surface; no tier gate, ever.
--   Full-canon sweep V1; extras-side marks wave 2 (extracanonical
--     sources may be QUOTED on cards where they are the source).
--   Reader-facing name "The Kingdom"; Blue Pill is the working title.
--   No dot glyphs anywhere on Kingdom surfaces.
--
-- Same curated-overlay shape as red_pill_verses (S204): fixed verse
-- text untouched, keyed overlay beside it, every row checker-gated
-- (Red Line #11 — the gathering is the scattered house coming home,
-- no false-inclusion leak, no spiritualized-Israel leak; Red Line #12;
-- Red Line #10 — grace completes the sentence; quote-don't-cite;
-- sacred names) before it lands.
--
-- One row per marked verse (UNIQUE(verse_id)); a verse carrying
-- several pairings gets one card that holds them together. A verse MAY
-- be a member of both the Witness and the Kingdom (separate tables,
-- both treatments render).
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + guarded index creation.
-- Seed rows land via session205_kingdom_seed_v1.sql (generated by
-- restoration-pipeline/_session205_build_kingdom_seed.py from
-- canon.json so every quote is exact restored text).
--
-- Run via: python3 api/apply_migration.py data-schema/migrations/session205_kingdom.sql
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS kingdom_verses (
    id              BIGSERIAL PRIMARY KEY,
    verse_id        BIGINT NOT NULL REFERENCES verses(id) ON DELETE CASCADE,
    strand          TEXT NOT NULL CHECK (strand IN
                        ('gathering','good_news','kingdom','grace','teaching')),
    strand_label    TEXT NOT NULL,        -- reader-facing tag: 'The gathering',
                                          -- 'The good news', 'The kingdom',
                                          -- 'Grace', 'The teaching'
    card_title      TEXT NOT NULL,        -- e.g. 'One fold, one shepherd — the
                                          -- two sticks made one in his hand'
    card_md         TEXT NOT NULL,        -- full come-and-see card (markdown; every
                                          -- verse quoted in full, stand-alone italics,
                                          -- citation at the end; sacred names intact)
    anchor_refs     TEXT[] NOT NULL DEFAULT '{}',  -- human-readable refs the card pairs
                                          -- (e.g. {'Ezekiel 37:15-22','John 10:16'})
    tier_required   content_tier NOT NULL DEFAULT 'free',
    last_reviewed_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (verse_id)
);

CREATE INDEX IF NOT EXISTS idx_kingdom_verse ON kingdom_verses(verse_id);
CREATE INDEX IF NOT EXISTS idx_kingdom_strand ON kingdom_verses(strand);

COMMENT ON TABLE kingdom_verses IS
    'THE KINGDOM (working title: Blue Pill) — the nothing-new overlay, S205. One row per verse that passes the nothing-new test: a new-testament teaching, act, or promise paired with the scripture it was taught from — nothing in the new testament is new; every beginning declared the end. Five strands: gathering, good_news, kingdom, grace, teaching. card_md is the come-and-see tap-card: both sides quoted in full, stand-alone italics. Every row is checker-gated (Red Line #11 — the gathering is the scattered house coming home, no false-inclusion leak; Red Line #12; Red Line #10 — grace as the means of return; quote-don''t-cite; sacred names) before it lands. Free tier — the proclamation surface. Register: the two sticks of Ezekiel 37:15-22 — metallic emerald + metallic gold joined in one pill.';

UPDATE schema_version
   SET version   = '1.0.0-phase-sessionD-session205',
       landed_at = NOW(),
       notes     = 'Session 205 — kingdom_verses landed: The Kingdom (nothing-new overlay) curated overlay, five concept strands, two-stick emerald+gold register, free tier, full-canon sweep V1. Seed v1 via session205_kingdom_seed_v1.sql. Prior version: 1.0.0-phase-sessionD-session204.'
 WHERE id = 1;

DO $verify$
DECLARE
    tbl_exists  BOOLEAN;
    uniq_exists BOOLEAN;
    tier_ok     BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'kingdom_verses'
    ) INTO tbl_exists;

    SELECT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'kingdom_verses'
          AND constraint_type = 'UNIQUE'
    ) INTO uniq_exists;

    SELECT tier_satisfies('free'::content_tier, 'free'::content_tier)
      INTO tier_ok;

    IF NOT tbl_exists OR NOT uniq_exists OR NOT tier_ok THEN
        RAISE EXCEPTION
            'session205 kingdom_verses verify failed: tbl=% uniq=% tier=%',
            tbl_exists, uniq_exists, tier_ok;
    END IF;

    RAISE NOTICE 'session205 kingdom_verses verified: table + unique + indexes landed.';
END
$verify$;

COMMIT;
