-- =====================================================================
-- Session 124 — Bookmarks + Notes V1 (Wheel 5 of the pre-launch sweep)
-- =====================================================================
-- Two W5 Free-tier surfaces per DESIGN_LANGUAGE.md §22:
--
--   1. NEW `bookmarks` table — single-verse flag with richer metadata
--      per Yoshi's S124 gate ("richer card with metadata" chosen over
--      a simple short_description-only sheet). Carries:
--        - short_description TEXT (multi-line, nullable; partner's
--          "why I saved this" note).
--        - tags TEXT[] (Postgres array; nullable; GIN-indexed for the
--          future W8 cross-bookmark hub queries).
--        - color_tint TEXT (nullable; CHECK reuses the §6 13-color
--          enum that highlights also use — partners learn one color
--          vocabulary across both surfaces).
--      UNIQUE (user_id, verse_id) — one bookmark per verse per partner;
--      re-bookmarking edits the existing row via ON CONFLICT DO UPDATE.
--
--   2. EXISTING `study_notes` table — relax the legacy CHECK that
--      required (chapter_id OR verse_id) NOT NULL. Free V1 single-
--      global-notepad needs to allow rows where BOTH are NULL (the
--      chrome-button free-form path locked at §22 — partner opens
--      Notes without an anchor + writes free-form). The CHECK was
--      defensive against client bugs from the original S9 $1.99-per-
--      verse design; the API layer enforces validity now, so the
--      CHECK adds nothing and blocks the V1 path.
--
-- Idempotent throughout — CREATE TABLE IF NOT EXISTS + DO-block guards
-- on constraints + dynamic-lookup drop for the auto-named study_notes
-- CHECK constraint (safer than DROP CONSTRAINT IF EXISTS by name,
-- since the autogenerated name varies by Postgres version + creation
-- order). Same shape as the S117 migration; re-runs are no-ops.
-- =====================================================================

\echo 'Session 124 — bookmarks + notes V1 migration starting...'
BEGIN;

-- ---------- 1. NEW bookmarks table -----------------------------------
-- One bookmark per (user, verse). short_description / tags / color_tint
-- all nullable — V1 partner can save a verse with no metadata (just the
-- flag) or fully labeled. color_tint enum mirrors the §6 13-color
-- HighlightColor enum exactly so partners learn one color vocabulary
-- across highlights and bookmarks.

CREATE TABLE IF NOT EXISTS bookmarks (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    verse_id            BIGINT NOT NULL REFERENCES verses(id) ON DELETE CASCADE,
    short_description   TEXT,
    tags                TEXT[],
    color_tint          TEXT
                            CHECK (color_tint IS NULL OR color_tint IN (
                                'neon_yellow', 'crimson', 'tangerine', 'honey',
                                'sage', 'emerald', 'teal', 'sky_blue',
                                'periwinkle', 'lilac', 'magenta', 'rose',
                                'parchment'
                            )),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One bookmark per verse per user. Re-bookmarking edits via ON CONFLICT
-- DO UPDATE in the API layer (POST /v1/bookmarks).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'bookmarks_user_verse_unique'
    ) THEN
        ALTER TABLE bookmarks
            ADD CONSTRAINT bookmarks_user_verse_unique
            UNIQUE (user_id, verse_id);
    END IF;
END $$;

-- Common-path query: list bookmarks for a chapter. Same shape as the
-- S113 verse_highlights index pair.
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_verse
    ON bookmarks(user_id, verse_id);

-- GIN index on tags for the W8 cross-bookmark hub (filter by tag).
-- Cheap to add now; the hub queries land already-fast at W8 without
-- a separate migration. NULL tags are fine; GIN handles them.
CREATE INDEX IF NOT EXISTS idx_bookmarks_tags_gin
    ON bookmarks USING GIN (tags);


-- ---------- 2. Relax study_notes CHECK ------------------------------
-- The original CHECK was inline (no explicit name). Postgres auto-
-- names table-level CHECKs as '{tablename}_check'. To be defensive
-- against name-drift across Postgres versions / creation order, look
-- the constraint up by its definition (references both chapter_id and
-- verse_id) and drop it by its actual name. Idempotent — if no
-- matching constraint exists (already-migrated state), the DO-block
-- is a NOTICE-only no-op.

DO $$
DECLARE
    cname TEXT;
BEGIN
    SELECT con.conname INTO cname
      FROM pg_constraint con
      JOIN pg_class rel ON rel.oid = con.conrelid
     WHERE rel.relname = 'study_notes'
       AND con.contype = 'c'  -- check constraint
       AND pg_get_constraintdef(con.oid) ILIKE '%chapter_id%verse_id%'
     LIMIT 1;
    IF cname IS NOT NULL THEN
        EXECUTE format('ALTER TABLE study_notes DROP CONSTRAINT %I', cname);
        RAISE NOTICE 'Session 124 — dropped study_notes CHECK constraint: %', cname;
    ELSE
        RAISE NOTICE 'Session 124 — no matching CHECK on study_notes (already relaxed?).';
    END IF;
END $$;

COMMIT;
\echo 'Session 124 — bookmarks + notes V1 migration complete.'
